/*
   simdmath.h - PS3 SDK umbrella for the libsimdmath SIMD math library.

   Makes the per-arch libsimdmath functions available as static inlines
   so reference-SDK samples that call sincosf4() / divf4() / rsqrtf4()
   link WITHOUT -lsimdmath.

   Mechanism:
     1. The public prototypes in simdmath/simdmath.h are hidden
        (__PS3DK_SIMDMATH_INLINE_NAMES); libsimdmath.a is built from the
        same header without it, so the archive keeps its external symbols.
     2. For each function this arch has, include its inline header
        (simdmath/_name.h), which defines a static inline _name.
     3. Define the public name as a static inline function calling _name
        (generated by sdk/libsimdmath/gen_inline_names.py), so a call
        inlines, &name needs no -lsimdmath, and C++ finds std::name.
     4. The f4fast forms are their own functions (below).

   The PPU and SPU function sets differ, so the SPU-only group is gated
   on __SPU__.
*/

#ifndef PS3TC_SIMDMATH_UMBRELLA_H
#define PS3TC_SIMDMATH_UMBRELLA_H

/* SPU vector math (vec_aos.h and friends) uses uintptr_t and relies on
   this header for <stdint.h>, as the reference SPU simdmath provides it. */
#include <stdint.h>
#define __PS3DK_SIMDMATH_INLINE_NAMES 1
#include <simdmath/simdmath.h>

#ifdef __SPU__
#include <spu_intrinsics.h>
#else
#include <altivec.h>
#endif

/* The vendor inlines initialise unsigned vectors from negative constants,
   which C++11 rejects as narrowing; they are correct C, so silence that one
   diagnostic for them in C++. */
#if defined(__cplusplus) && defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wnarrowing"
#endif

/* ---- BEGIN generated declarations (sdk/libsimdmath/gen_inline_names.py) ---- */
/* Declared before the inline implementations: some of them call other
 * public names (_atan2f4 calls divf4), which must resolve to these. */
static inline vector signed int absi4(vector signed int a0);
static inline vector float acosf4(vector float a0);
static inline vector float asinf4(vector float a0);
static inline vector float atan2f4(vector float a0, vector float a1);
static inline vector float atanf4(vector float a0);
static inline vector float cbrtf4(vector float a0);
static inline vector float ceilf4(vector float a0);
static inline vector float copysignf4(vector float a0, vector float a1);
static inline vector float cosf4(vector float a0);
static inline vector float divf4(vector float a0, vector float a1);
static inline divi4_t divi4(vector signed int a0, vector signed int a1);
static inline vector float exp2f4(vector float a0);
static inline vector float expf4(vector float a0);
static inline vector float expm1f4(vector float a0);
static inline vector float fabsf4(vector float a0);
static inline vector float fdimf4(vector float a0, vector float a1);
static inline vector float floorf4(vector float a0);
static inline vector float fmaf4(vector float a0, vector float a1, vector float a2);
static inline vector float fmaxf4(vector float a0, vector float a1);
static inline vector float fminf4(vector float a0, vector float a1);
static inline vector float fmodf4(vector float a0, vector float a1);
static inline vector float frexpf4(vector float a0, vector signed int * a1);
static inline vector float hypotf4(vector float a0, vector float a1);
static inline vector signed int ilogbf4(vector float a0);
static inline vector float ldexpf4(vector float a0, vector signed int a1);
static inline vector float log10f4(vector float a0);
static inline vector float log1pf4(vector float a0);
static inline vector float log2f4(vector float a0);
static inline vector float logbf4(vector float a0);
static inline vector float logf4(vector float a0);
static inline vector float modff4(vector float a0, vector float * a1);
static inline vector float negatef4(vector float a0);
static inline vector signed int negatei4(vector signed int a0);
static inline vector float powf4(vector float a0, vector float a1);
static inline vector float recipf4(vector float a0);
static inline vector float remainderf4(vector float a0, vector float a1);
static inline vector float rsqrtf4(vector float a0);
static inline void sincosf4(vector float a0, vector float * a1, vector float * a2);
static inline vector float sinf4(vector float a0);
static inline vector float sqrtf4(vector float a0);
static inline vector float tanf4(vector float a0);
static inline vector float truncf4(vector float a0);
#ifdef __SPU__
static inline vector double ceild2(vector double a0);
static inline vector double copysignd2(vector double a0, vector double a1);
static inline vector double cosd2(vector double a0);
static inline vector double divd2(vector double a0, vector double a1);
static inline divu4_t divu4(vector unsigned int a0, vector unsigned int a1);
static inline vector double fabsd2(vector double a0);
static inline vector double fdimd2(vector double a0, vector double a1);
static inline vector double floord2(vector double a0);
static inline vector double fmad2(vector double a0, vector double a1, vector double a2);
static inline vector double fmaxd2(vector double a0, vector double a1);
static inline vector double fmind2(vector double a0, vector double a1);
static inline vector double fmodd2(vector double a0, vector double a1);
static inline vector signed long long fpclassifyd2(vector double a0);
static inline vector signed int fpclassifyf4(vector float a0);
static inline vector double frexpd2(vector double a0, vector signed long long * a1);
static inline vector double hypotd2(vector double a0, vector double a1);
static inline vector signed long long ilogbd2(vector double a0);
static inline vector signed int irintf4(vector float a0);
static inline vector signed int iroundf4(vector float a0);
static inline vector unsigned long long is0denormd2(vector double a0);
static inline vector unsigned int is0denormf4(vector float a0);
static inline vector unsigned long long isequald2(vector double a0, vector double a1);
static inline vector unsigned int isequalf4(vector float a0, vector float a1);
static inline vector unsigned long long isfinited2(vector double a0);
static inline vector unsigned int isfinitef4(vector float a0);
static inline vector unsigned long long isgreaterd2(vector double a0, vector double a1);
static inline vector unsigned long long isgreaterequald2(vector double a0, vector double a1);
static inline vector unsigned int isgreaterequalf4(vector float a0, vector float a1);
static inline vector unsigned int isgreaterf4(vector float a0, vector float a1);
static inline vector unsigned long long isinfd2(vector double a0);
static inline vector unsigned int isinff4(vector float a0);
static inline vector unsigned long long islessd2(vector double a0, vector double a1);
static inline vector unsigned long long islessequald2(vector double a0, vector double a1);
static inline vector unsigned int islessequalf4(vector float a0, vector float a1);
static inline vector unsigned int islessf4(vector float a0, vector float a1);
static inline vector unsigned long long islessgreaterd2(vector double a0, vector double a1);
static inline vector unsigned int islessgreaterf4(vector float a0, vector float a1);
static inline vector unsigned long long isnand2(vector double a0);
static inline vector unsigned int isnanf4(vector float a0);
static inline vector unsigned long long isnormald2(vector double a0);
static inline vector unsigned int isnormalf4(vector float a0);
static inline vector unsigned long long isunorderedd2(vector double a0, vector double a1);
static inline vector unsigned int isunorderedf4(vector float a0, vector float a1);
static inline vector double ldexpd2(vector double a0, vector signed long long a1);
static inline vector signed long long llabsi2(vector signed long long a0);
static inline lldivi2_t lldivi2(vector signed long long a0, vector signed long long a1);
static inline lldivu2_t lldivu2(vector unsigned long long a0, vector unsigned long long a1);
static inline vector signed long long llrintd2(vector double a0);
static inline llroundf4_t llrintf4(vector float a0);
static inline vector signed long long llroundd2(vector double a0);
static inline llroundf4_t llroundf4(vector float a0);
static inline vector double logbd2(vector double a0);
static inline vector double modfd2(vector double a0, vector double * a1);
static inline vector double nearbyintd2(vector double a0);
static inline vector float nearbyintf4(vector float a0);
static inline vector double negated2(vector double a0);
static inline vector signed long long negatell2(vector signed long long a0);
static inline vector double nextafterd2(vector double a0, vector double a1);
static inline vector float nextafterf4(vector float a0, vector float a1);
static inline vector double recipd2(vector double a0);
static inline vector double remainderd2(vector double a0, vector double a1);
static inline vector double remquod2(vector double a0, vector double a1, vector signed long long * a2);
static inline vector float remquof4(vector float a0, vector float a1, vector signed int * a2);
static inline vector double rintd2(vector double a0);
static inline vector float rintf4(vector float a0);
static inline vector double roundd2(vector double a0);
static inline vector float roundf4(vector float a0);
static inline vector double rsqrtd2(vector double a0);
static inline vector double scalbllnd2(vector double a0, vector signed long long a1);
static inline vector float scalbnf4(vector float a0, vector signed int a1);
static inline vector unsigned long long signbitd2(vector double a0);
static inline vector unsigned int signbitf4(vector float a0);
static inline void sincosd2(vector double a0, vector double * a1, vector double * a2);
static inline vector double sind2(vector double a0);
static inline vector double sqrtd2(vector double a0);
static inline vector double tand2(vector double a0);
static inline vector double truncd2(vector double a0);
#endif /* __SPU__ */
/* ---- END generated declarations ---- */

/* ---- inline implementations shared by PPU + SPU ---- */
#include <simdmath/_absi4.h>
#include <simdmath/_acosf4.h>
#include <simdmath/_asinf4.h>
#include <simdmath/_atan2f4.h>
#include <simdmath/_atanf4.h>
#include <simdmath/_cbrtf4.h>
#include <simdmath/_ceilf4.h>
#include <simdmath/_copysignf4.h>
#include <simdmath/_cosf4.h>
#include <simdmath/_divf4.h>
#include <simdmath/_divi4.h>
#include <simdmath/_exp2f4.h>
#include <simdmath/_expf4.h>
#include <simdmath/_expm1f4.h>
#include <simdmath/_fabsf4.h>
#include <simdmath/_fdimf4.h>
#include <simdmath/_floorf4.h>
#include <simdmath/_fmaf4.h>
#include <simdmath/_fmaxf4.h>
#include <simdmath/_fminf4.h>
#include <simdmath/_fmodf4.h>
#include <simdmath/_frexpf4.h>
#include <simdmath/_hypotf4.h>
#include <simdmath/_ilogbf4.h>
#include <simdmath/_ldexpf4.h>
#include <simdmath/_log10f4.h>
#include <simdmath/_log1pf4.h>
#include <simdmath/_log2f4.h>
#include <simdmath/_logbf4.h>
#include <simdmath/_logf4.h>
#include <simdmath/_modff4.h>
#include <simdmath/_negatef4.h>
#include <simdmath/_negatei4.h>
#include <simdmath/_powf4.h>
#include <simdmath/_recipf4.h>
#include <simdmath/_remainderf4.h>
#include <simdmath/_rsqrtf4.h>
#include <simdmath/_sincosf4.h>
#include <simdmath/_sinf4.h>
#include <simdmath/_sqrtf4.h>
#include <simdmath/_tanf4.h>
#include <simdmath/_truncf4.h>

/* ---- SPU-only inline implementations ---- */
#ifdef __SPU__
#include <simdmath/_ceild2.h>
#include <simdmath/_copysignd2.h>
#include <simdmath/_cosd2.h>
#include <simdmath/_divd2.h>
#include <simdmath/_divu4.h>
#include <simdmath/_fabsd2.h>
#include <simdmath/_fdimd2.h>
#include <simdmath/_floord2.h>
#include <simdmath/_fmad2.h>
#include <simdmath/_fmaxd2.h>
#include <simdmath/_fmind2.h>
#include <simdmath/_fmodd2.h>
#include <simdmath/_fpclassifyd2.h>
#include <simdmath/_fpclassifyf4.h>
#include <simdmath/_frexpd2.h>
#include <simdmath/_hypotd2.h>
#include <simdmath/_ilogbd2.h>
#include <simdmath/_irintf4.h>
#include <simdmath/_iroundf4.h>
#include <simdmath/_is0denormd2.h>
#include <simdmath/_is0denormf4.h>
#include <simdmath/_isequald2.h>
#include <simdmath/_isequalf4.h>
#include <simdmath/_isfinited2.h>
#include <simdmath/_isfinitef4.h>
#include <simdmath/_isgreaterd2.h>
#include <simdmath/_isgreaterequald2.h>
#include <simdmath/_isgreaterequalf4.h>
#include <simdmath/_isgreaterf4.h>
#include <simdmath/_isinfd2.h>
#include <simdmath/_isinff4.h>
#include <simdmath/_islessd2.h>
#include <simdmath/_islessequald2.h>
#include <simdmath/_islessequalf4.h>
#include <simdmath/_islessf4.h>
#include <simdmath/_islessgreaterd2.h>
#include <simdmath/_islessgreaterf4.h>
#include <simdmath/_isnand2.h>
#include <simdmath/_isnanf4.h>
#include <simdmath/_isnormald2.h>
#include <simdmath/_isnormalf4.h>
#include <simdmath/_isunorderedd2.h>
#include <simdmath/_isunorderedf4.h>
#include <simdmath/_ldexpd2.h>
#include <simdmath/_llabsi2.h>
#include <simdmath/_lldivi2.h>
#include <simdmath/_lldivu2.h>
#include <simdmath/_llrintd2.h>
#include <simdmath/_llrintf4.h>
#include <simdmath/_llroundd2.h>
#include <simdmath/_llroundf4.h>
#include <simdmath/_logbd2.h>
#include <simdmath/_modfd2.h>
#include <simdmath/_nearbyintd2.h>
#include <simdmath/_nearbyintf4.h>
#include <simdmath/_negated2.h>
#include <simdmath/_negatell2.h>
#include <simdmath/_nextafterd2.h>
#include <simdmath/_nextafterf4.h>
#include <simdmath/_recipd2.h>
#include <simdmath/_remainderd2.h>
#include <simdmath/_remquod2.h>
#include <simdmath/_remquof4.h>
#include <simdmath/_rintd2.h>
#include <simdmath/_rintf4.h>
#include <simdmath/_roundd2.h>
#include <simdmath/_roundf4.h>
#include <simdmath/_rsqrtd2.h>
#include <simdmath/_scalbllnd2.h>
#include <simdmath/_scalbnf4.h>
#include <simdmath/_signbitd2.h>
#include <simdmath/_signbitf4.h>
#include <simdmath/_sincosd2.h>
#include <simdmath/_sind2.h>
#include <simdmath/_sqrtd2.h>
#include <simdmath/_tand2.h>
#include <simdmath/_truncd2.h>
#endif /* __SPU__ */

#if defined(__cplusplus) && defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

/* ---- BEGIN generated public names (sdk/libsimdmath/gen_inline_names.py) ---- */
/* Public names: static inline functions over the per-arch inlines.  A call
 * inlines; taking the address needs no -lsimdmath; C++ also finds them as
 * std::name. */
static inline vector signed int absi4(vector signed int a0) { return _absi4(a0); }
static inline vector float acosf4(vector float a0) { return _acosf4(a0); }
static inline vector float asinf4(vector float a0) { return _asinf4(a0); }
static inline vector float atan2f4(vector float a0, vector float a1) { return _atan2f4(a0, a1); }
static inline vector float atanf4(vector float a0) { return _atanf4(a0); }
static inline vector float cbrtf4(vector float a0) { return _cbrtf4(a0); }
static inline vector float ceilf4(vector float a0) { return _ceilf4(a0); }
static inline vector float copysignf4(vector float a0, vector float a1) { return _copysignf4(a0, a1); }
static inline vector float cosf4(vector float a0) { return _cosf4(a0); }
static inline vector float divf4(vector float a0, vector float a1) { return _divf4(a0, a1); }
static inline divi4_t divi4(vector signed int a0, vector signed int a1) { return _divi4(a0, a1); }
static inline vector float exp2f4(vector float a0) { return _exp2f4(a0); }
static inline vector float expf4(vector float a0) { return _expf4(a0); }
static inline vector float expm1f4(vector float a0) { return _expm1f4(a0); }
static inline vector float fabsf4(vector float a0) { return _fabsf4(a0); }
static inline vector float fdimf4(vector float a0, vector float a1) { return _fdimf4(a0, a1); }
static inline vector float floorf4(vector float a0) { return _floorf4(a0); }
static inline vector float fmaf4(vector float a0, vector float a1, vector float a2) { return _fmaf4(a0, a1, a2); }
static inline vector float fmaxf4(vector float a0, vector float a1) { return _fmaxf4(a0, a1); }
static inline vector float fminf4(vector float a0, vector float a1) { return _fminf4(a0, a1); }
static inline vector float fmodf4(vector float a0, vector float a1) { return _fmodf4(a0, a1); }
static inline vector float frexpf4(vector float a0, vector signed int * a1) { return _frexpf4(a0, a1); }
static inline vector float hypotf4(vector float a0, vector float a1) { return _hypotf4(a0, a1); }
static inline vector signed int ilogbf4(vector float a0) { return _ilogbf4(a0); }
static inline vector float ldexpf4(vector float a0, vector signed int a1) { return _ldexpf4(a0, a1); }
static inline vector float log10f4(vector float a0) { return _log10f4(a0); }
static inline vector float log1pf4(vector float a0) { return _log1pf4(a0); }
static inline vector float log2f4(vector float a0) { return _log2f4(a0); }
static inline vector float logbf4(vector float a0) { return _logbf4(a0); }
static inline vector float logf4(vector float a0) { return _logf4(a0); }
static inline vector float modff4(vector float a0, vector float * a1) { return _modff4(a0, a1); }
static inline vector float negatef4(vector float a0) { return _negatef4(a0); }
static inline vector signed int negatei4(vector signed int a0) { return _negatei4(a0); }
static inline vector float powf4(vector float a0, vector float a1) { return _powf4(a0, a1); }
static inline vector float recipf4(vector float a0) { return _recipf4(a0); }
static inline vector float remainderf4(vector float a0, vector float a1) { return _remainderf4(a0, a1); }
static inline vector float rsqrtf4(vector float a0) { return _rsqrtf4(a0); }
static inline void sincosf4(vector float a0, vector float * a1, vector float * a2) { _sincosf4(a0, a1, a2); }
static inline vector float sinf4(vector float a0) { return _sinf4(a0); }
static inline vector float sqrtf4(vector float a0) { return _sqrtf4(a0); }
static inline vector float tanf4(vector float a0) { return _tanf4(a0); }
static inline vector float truncf4(vector float a0) { return _truncf4(a0); }

#ifdef __SPU__
static inline vector double ceild2(vector double a0) { return _ceild2(a0); }
static inline vector double copysignd2(vector double a0, vector double a1) { return _copysignd2(a0, a1); }
static inline vector double cosd2(vector double a0) { return _cosd2(a0); }
static inline vector double divd2(vector double a0, vector double a1) { return _divd2(a0, a1); }
static inline divu4_t divu4(vector unsigned int a0, vector unsigned int a1) { return _divu4(a0, a1); }
static inline vector double fabsd2(vector double a0) { return _fabsd2(a0); }
static inline vector double fdimd2(vector double a0, vector double a1) { return _fdimd2(a0, a1); }
static inline vector double floord2(vector double a0) { return _floord2(a0); }
static inline vector double fmad2(vector double a0, vector double a1, vector double a2) { return _fmad2(a0, a1, a2); }
static inline vector double fmaxd2(vector double a0, vector double a1) { return _fmaxd2(a0, a1); }
static inline vector double fmind2(vector double a0, vector double a1) { return _fmind2(a0, a1); }
static inline vector double fmodd2(vector double a0, vector double a1) { return _fmodd2(a0, a1); }
static inline vector signed long long fpclassifyd2(vector double a0) { return _fpclassifyd2(a0); }
static inline vector signed int fpclassifyf4(vector float a0) { return _fpclassifyf4(a0); }
static inline vector double frexpd2(vector double a0, vector signed long long * a1) { return _frexpd2(a0, a1); }
static inline vector double hypotd2(vector double a0, vector double a1) { return _hypotd2(a0, a1); }
static inline vector signed long long ilogbd2(vector double a0) { return _ilogbd2(a0); }
static inline vector signed int irintf4(vector float a0) { return _irintf4(a0); }
static inline vector signed int iroundf4(vector float a0) { return _iroundf4(a0); }
static inline vector unsigned long long is0denormd2(vector double a0) { return _is0denormd2(a0); }
static inline vector unsigned int is0denormf4(vector float a0) { return _is0denormf4(a0); }
static inline vector unsigned long long isequald2(vector double a0, vector double a1) { return _isequald2(a0, a1); }
static inline vector unsigned int isequalf4(vector float a0, vector float a1) { return _isequalf4(a0, a1); }
static inline vector unsigned long long isfinited2(vector double a0) { return _isfinited2(a0); }
static inline vector unsigned int isfinitef4(vector float a0) { return _isfinitef4(a0); }
static inline vector unsigned long long isgreaterd2(vector double a0, vector double a1) { return _isgreaterd2(a0, a1); }
static inline vector unsigned long long isgreaterequald2(vector double a0, vector double a1) { return _isgreaterequald2(a0, a1); }
static inline vector unsigned int isgreaterequalf4(vector float a0, vector float a1) { return _isgreaterequalf4(a0, a1); }
static inline vector unsigned int isgreaterf4(vector float a0, vector float a1) { return _isgreaterf4(a0, a1); }
static inline vector unsigned long long isinfd2(vector double a0) { return _isinfd2(a0); }
static inline vector unsigned int isinff4(vector float a0) { return _isinff4(a0); }
static inline vector unsigned long long islessd2(vector double a0, vector double a1) { return _islessd2(a0, a1); }
static inline vector unsigned long long islessequald2(vector double a0, vector double a1) { return _islessequald2(a0, a1); }
static inline vector unsigned int islessequalf4(vector float a0, vector float a1) { return _islessequalf4(a0, a1); }
static inline vector unsigned int islessf4(vector float a0, vector float a1) { return _islessf4(a0, a1); }
static inline vector unsigned long long islessgreaterd2(vector double a0, vector double a1) { return _islessgreaterd2(a0, a1); }
static inline vector unsigned int islessgreaterf4(vector float a0, vector float a1) { return _islessgreaterf4(a0, a1); }
static inline vector unsigned long long isnand2(vector double a0) { return _isnand2(a0); }
static inline vector unsigned int isnanf4(vector float a0) { return _isnanf4(a0); }
static inline vector unsigned long long isnormald2(vector double a0) { return _isnormald2(a0); }
static inline vector unsigned int isnormalf4(vector float a0) { return _isnormalf4(a0); }
static inline vector unsigned long long isunorderedd2(vector double a0, vector double a1) { return _isunorderedd2(a0, a1); }
static inline vector unsigned int isunorderedf4(vector float a0, vector float a1) { return _isunorderedf4(a0, a1); }
static inline vector double ldexpd2(vector double a0, vector signed long long a1) { return _ldexpd2(a0, a1); }
static inline vector signed long long llabsi2(vector signed long long a0) { return _llabsi2(a0); }
static inline lldivi2_t lldivi2(vector signed long long a0, vector signed long long a1) { return _lldivi2(a0, a1); }
static inline lldivu2_t lldivu2(vector unsigned long long a0, vector unsigned long long a1) { return _lldivu2(a0, a1); }
static inline vector signed long long llrintd2(vector double a0) { return _llrintd2(a0); }
static inline llroundf4_t llrintf4(vector float a0) { return _llrintf4(a0); }
static inline vector signed long long llroundd2(vector double a0) { return _llroundd2(a0); }
static inline llroundf4_t llroundf4(vector float a0) { return _llroundf4(a0); }
static inline vector double logbd2(vector double a0) { return _logbd2(a0); }
static inline vector double modfd2(vector double a0, vector double * a1) { return _modfd2(a0, a1); }
static inline vector double nearbyintd2(vector double a0) { return _nearbyintd2(a0); }
static inline vector float nearbyintf4(vector float a0) { return _nearbyintf4(a0); }
static inline vector double negated2(vector double a0) { return _negated2(a0); }
static inline vector signed long long negatell2(vector signed long long a0) { return _negatell2(a0); }
static inline vector double nextafterd2(vector double a0, vector double a1) { return _nextafterd2(a0, a1); }
static inline vector float nextafterf4(vector float a0, vector float a1) { return _nextafterf4(a0, a1); }
static inline vector double recipd2(vector double a0) { return _recipd2(a0); }
static inline vector double remainderd2(vector double a0, vector double a1) { return _remainderd2(a0, a1); }
static inline vector double remquod2(vector double a0, vector double a1, vector signed long long * a2) { return _remquod2(a0, a1, a2); }
static inline vector float remquof4(vector float a0, vector float a1, vector signed int * a2) { return _remquof4(a0, a1, a2); }
static inline vector double rintd2(vector double a0) { return _rintd2(a0); }
static inline vector float rintf4(vector float a0) { return _rintf4(a0); }
static inline vector double roundd2(vector double a0) { return _roundd2(a0); }
static inline vector float roundf4(vector float a0) { return _roundf4(a0); }
static inline vector double rsqrtd2(vector double a0) { return _rsqrtd2(a0); }
static inline vector double scalbllnd2(vector double a0, vector signed long long a1) { return _scalbllnd2(a0, a1); }
static inline vector float scalbnf4(vector float a0, vector signed int a1) { return _scalbnf4(a0, a1); }
static inline vector unsigned long long signbitd2(vector double a0) { return _signbitd2(a0); }
static inline vector unsigned int signbitf4(vector float a0) { return _signbitf4(a0); }
static inline void sincosd2(vector double a0, vector double * a1, vector double * a2) { _sincosd2(a0, a1, a2); }
static inline vector double sind2(vector double a0) { return _sind2(a0); }
static inline vector double sqrtd2(vector double a0) { return _sqrtd2(a0); }
static inline vector double tand2(vector double a0) { return _tand2(a0); }
static inline vector double truncd2(vector double a0) { return _truncd2(a0); }
#endif /* __SPU__ */

#ifdef __cplusplus
namespace std {
using ::absi4;
using ::acosf4;
using ::asinf4;
using ::atan2f4;
using ::atanf4;
using ::cbrtf4;
using ::ceilf4;
using ::copysignf4;
using ::cosf4;
using ::divf4;
using ::divi4;
using ::exp2f4;
using ::expf4;
using ::expm1f4;
using ::fabsf4;
using ::fdimf4;
using ::floorf4;
using ::fmaf4;
using ::fmaxf4;
using ::fminf4;
using ::fmodf4;
using ::frexpf4;
using ::hypotf4;
using ::ilogbf4;
using ::ldexpf4;
using ::log10f4;
using ::log1pf4;
using ::log2f4;
using ::logbf4;
using ::logf4;
using ::modff4;
using ::negatef4;
using ::negatei4;
using ::powf4;
using ::recipf4;
using ::remainderf4;
using ::rsqrtf4;
using ::sincosf4;
using ::sinf4;
using ::sqrtf4;
using ::tanf4;
using ::truncf4;
#ifdef __SPU__
using ::ceild2;
using ::copysignd2;
using ::cosd2;
using ::divd2;
using ::divu4;
using ::fabsd2;
using ::fdimd2;
using ::floord2;
using ::fmad2;
using ::fmaxd2;
using ::fmind2;
using ::fmodd2;
using ::fpclassifyd2;
using ::fpclassifyf4;
using ::frexpd2;
using ::hypotd2;
using ::ilogbd2;
using ::irintf4;
using ::iroundf4;
using ::is0denormd2;
using ::is0denormf4;
using ::isequald2;
using ::isequalf4;
using ::isfinited2;
using ::isfinitef4;
using ::isgreaterd2;
using ::isgreaterequald2;
using ::isgreaterequalf4;
using ::isgreaterf4;
using ::isinfd2;
using ::isinff4;
using ::islessd2;
using ::islessequald2;
using ::islessequalf4;
using ::islessf4;
using ::islessgreaterd2;
using ::islessgreaterf4;
using ::isnand2;
using ::isnanf4;
using ::isnormald2;
using ::isnormalf4;
using ::isunorderedd2;
using ::isunorderedf4;
using ::ldexpd2;
using ::llabsi2;
using ::lldivi2;
using ::lldivu2;
using ::llrintd2;
using ::llrintf4;
using ::llroundd2;
using ::llroundf4;
using ::logbd2;
using ::modfd2;
using ::nearbyintd2;
using ::nearbyintf4;
using ::negated2;
using ::negatell2;
using ::nextafterd2;
using ::nextafterf4;
using ::recipd2;
using ::remainderd2;
using ::remquod2;
using ::remquof4;
using ::rintd2;
using ::rintf4;
using ::roundd2;
using ::roundf4;
using ::rsqrtd2;
using ::scalbllnd2;
using ::scalbnf4;
using ::signbitd2;
using ::signbitf4;
using ::sincosd2;
using ::sind2;
using ::sqrtd2;
using ::tand2;
using ::truncd2;
#endif
}
#endif
/* ---- END generated public names ---- */

/* ---- fast forms ----
 * divf4fast, recipf4fast and rsqrtf4fast are the hardware estimates (about
 * 12 bits: the PPU vrefp / vrsqrtefp, the SPU frest / frsqest with their
 * interpolation).  cbrtf4fast is cbrtf4.  The others are in
 * simdmath/fastf4.h, over the vector layer defined here; see there for each
 * form's accuracy and domain. */
#ifdef __SPU__
static inline vector float recipf4fast(vector float x) { return spu_re(x); }
static inline vector float rsqrtf4fast(vector float x) { return spu_rsqrte(x); }
static inline vector float divf4fast(vector float n, vector float d) { return spu_mul(n, spu_re(d)); }

typedef vector float __fm_vf;
typedef vector unsigned int __fm_vu;
typedef vector signed int __fm_vi;
static inline __fm_vf __fm_splat(float f) { return spu_splats(f); }
static inline __fm_vi __fm_isplat(int n) { return spu_splats(n); }
static inline __fm_vf __fm_madd(__fm_vf a, __fm_vf b, __fm_vf c) { return spu_madd(a, b, c); }
static inline __fm_vf __fm_nmsub(__fm_vf a, __fm_vf b, __fm_vf c) { return spu_nmsub(a, b, c); }
static inline __fm_vf __fm_mul(__fm_vf a, __fm_vf b) { return spu_mul(a, b); }
static inline __fm_vf __fm_add(__fm_vf a, __fm_vf b) { return spu_add(a, b); }
static inline __fm_vf __fm_sub(__fm_vf a, __fm_vf b) { return spu_sub(a, b); }
static inline __fm_vf __fm_sel(__fm_vf a, __fm_vf b, __fm_vu m) { return spu_sel(a, b, m); }
static inline __fm_vu __fm_cmpgt(__fm_vf a, __fm_vf b) { return spu_cmpgt(a, b); }
static inline __fm_vu __fm_cmpeq(__fm_vf a, __fm_vf b) { return spu_cmpeq(a, b); }
static inline __fm_vf __fm_re(__fm_vf x) { return spu_re(x); }
static inline __fm_vf __fm_rsqrte(__fm_vf x) { return spu_rsqrte(x); }
static inline __fm_vi __fm_cts(__fm_vf x) { return spu_convts(x, 0); }
static inline __fm_vf __fm_ctf(__fm_vi i) { return spu_convtf(i, 0); }
static inline __fm_vi __fm_iadd(__fm_vi a, __fm_vi b) { return spu_add(a, b); }
static inline __fm_vi __fm_isub(__fm_vi a, __fm_vi b) { return spu_sub(a, b); }
static inline __fm_vi __fm_sl(__fm_vi a, int n) { return spu_sl(a, (unsigned int)n); }
static inline __fm_vu __fm_sr(__fm_vu a, int n) { return spu_rlmask(a, -n); }
#else
static inline vector float recipf4fast(vector float x) { return vec_re(x); }
static inline vector float rsqrtf4fast(vector float x) { return vec_rsqrte(x); }
static inline vector float divf4fast(vector float n, vector float d)
{ return vec_madd(n, vec_re(d), __vec_splatsf4(-0.0f)); }

typedef vector float __fm_vf;
typedef vector unsigned int __fm_vu;
typedef vector signed int __fm_vi;
#define __FM_VEC_ESTIMATES 1
static inline __fm_vf __fm_splat(float f) { return (__fm_vf){ f, f, f, f }; }
static inline __fm_vi __fm_isplat(int n) { return (__fm_vi){ n, n, n, n }; }
static inline __fm_vf __fm_madd(__fm_vf a, __fm_vf b, __fm_vf c) { return vec_madd(a, b, c); }
static inline __fm_vf __fm_nmsub(__fm_vf a, __fm_vf b, __fm_vf c) { return vec_nmsub(a, b, c); }
static inline __fm_vf __fm_mul(__fm_vf a, __fm_vf b) { return vec_madd(a, b, __fm_splat(-0.0f)); }
static inline __fm_vf __fm_add(__fm_vf a, __fm_vf b) { return vec_add(a, b); }
static inline __fm_vf __fm_sub(__fm_vf a, __fm_vf b) { return vec_sub(a, b); }
static inline __fm_vf __fm_sel(__fm_vf a, __fm_vf b, __fm_vu m) { return vec_sel(a, b, m); }
static inline __fm_vu __fm_cmpgt(__fm_vf a, __fm_vf b) { return (__fm_vu)vec_cmpgt(a, b); }
static inline __fm_vu __fm_cmpeq(__fm_vf a, __fm_vf b) { return (__fm_vu)vec_cmpeq(a, b); }
static inline __fm_vf __fm_re(__fm_vf x) { return vec_re(x); }
static inline __fm_vf __fm_rsqrte(__fm_vf x) { return vec_rsqrte(x); }
static inline __fm_vi __fm_cts(__fm_vf x) { return vec_cts(x, 0); }
static inline __fm_vf __fm_ctf(__fm_vi i) { return vec_ctf(i, 0); }
static inline __fm_vi __fm_iadd(__fm_vi a, __fm_vi b) { return vec_add(a, b); }
static inline __fm_vi __fm_isub(__fm_vi a, __fm_vi b) { return vec_sub(a, b); }
static inline __fm_vi __fm_sl(__fm_vi a, int n) { return vec_sl(a, (__fm_vu){ (unsigned)n, (unsigned)n, (unsigned)n, (unsigned)n }); }
static inline __fm_vu __fm_sr(__fm_vu a, int n) { return vec_sr(a, (__fm_vu){ (unsigned)n, (unsigned)n, (unsigned)n, (unsigned)n }); }
static inline __fm_vf __fm_expte(__fm_vf x) { return vec_expte(x); }
static inline __fm_vf __fm_loge(__fm_vf x) { return vec_loge(x); }
#endif
#include <simdmath/fastf4.h>

static inline vector float acosf4fast(vector float x) { return __fm_acosf4fast(x); }
static inline vector float asinf4fast(vector float x) { return __fm_asinf4fast(x); }
static inline vector float atan2f4fast(vector float y, vector float x) { return __fm_atan2f4fast(y, x); }
static inline vector float atanf4fast(vector float x) { return __fm_atanf4fast(x); }
static inline vector float cbrtf4fast(vector float x) { return _cbrtf4(x); }
static inline vector float cosf4fast(vector float x) { return __fm_cosf4fast(x); }
static inline vector float exp2f4fast(vector float x) { return __fm_exp2f4fast(x); }
static inline vector float expf4fast(vector float x) { return __fm_expf4fast(x); }
static inline vector float expm1f4fast(vector float x) { return __fm_expm1f4fast(x); }
static inline vector float log10f4fast(vector float x) { return __fm_log10f4fast(x); }
static inline vector float log1pf4fast(vector float x) { return __fm_log1pf4fast(x); }
static inline vector float log2f4fast(vector float x) { return __fm_log2f4fast(x); }
static inline vector float logf4fast(vector float x) { return __fm_logf4fast(x); }
static inline vector float powf4fast(vector float x, vector float y) { return __fm_powf4fast(x, y); }
static inline void sincosf4fast(vector float x, vector float *s, vector float *c) { __fm_sincosf4fast(x, s, c); }
static inline vector float sinf4fast(vector float x) { return __fm_sinf4fast(x); }
static inline vector float sqrtf4fast(vector float x) { return __fm_sqrtf4fast(x); }
static inline vector float tanf4fast(vector float x) { return __fm_tanf4fast(x); }
#ifdef __cplusplus
namespace std {
using ::recipf4fast; using ::rsqrtf4fast; using ::divf4fast; using ::acosf4fast; using ::asinf4fast;
using ::atan2f4fast; using ::atanf4fast; using ::cbrtf4fast; using ::cosf4fast; using ::exp2f4fast;
using ::expf4fast; using ::expm1f4fast; using ::log10f4fast; using ::log1pf4fast; using ::log2f4fast;
using ::logf4fast; using ::powf4fast; using ::sincosf4fast; using ::sinf4fast; using ::sqrtf4fast;
using ::tanf4fast;
}
#endif

/* ---- SPU two-lane double comparisons (new; thin over the existing is* d2 primitives) ---- */
/*     cmpeqd2(x,y)       == isequal(x,y)   */
/*     cmpged2(x,y)       == !(x<y) == islessequal(y,x)   */
/*     cmpgtd2(x,y)       == isgreater(x,y)   */
/*     cmpinfd2(x)        == isinf(x)   */
/*     cmpnand2(x)        == isnan(x)   */
/*     cmpnegsignd2(x)    == signbit(x)   */
/*     cmpzerodenormd2(x) == zero_or_denorm(x)   */
/* SPU-only because the PPU side of libsimdmath has no double lane. */
#ifdef __SPU__
static inline vector unsigned long long
cmpeqd2      (vector double x, vector double y) { return _isequald2    (x, y); }
static inline vector unsigned long long
cmpged2      (vector double x, vector double y) { return _islessequald2(y, x); }
static inline vector unsigned long long
cmpgtd2      (vector double x, vector double y) { return _isgreaterd2  (x, y); }
static inline vector unsigned long long
cmpinfd2     (vector double x)                   { return _isinfd2      (x); }
static inline vector unsigned long long
cmpnand2     (vector double x)                   { return _isnand2      (x); }
static inline vector unsigned long long
cmpnegsignd2 (vector double x)                   { return _signbitd2    (x); }
static inline vector unsigned long long
cmpzerodenormd2(vector double x)                 { return _is0denormd2  (x); }
#endif /* __SPU__ */

#endif /* PS3TC_SIMDMATH_UMBRELLA_H */
