/* cell/gcm/gcm_command_cpp_explicit.h - cell::Gcm::CellGcmContext.
 *
 * GENERATED by scripts/gen-gcm-context-cpp.py from the SDK's GCM command
 * headers; do not edit.  One member per context-taking cellGcm* command,
 * named without the prefix: context.SetVertexDataArray(...) is
 * cellGcmSetVertexDataArray(&context, ...).  The class adds no data, so a
 * CellGcmContextData (gCellGcmCurrentContext, say) can be used as one.
 */
#ifndef __PS3DK_CELL_GCM_COMMAND_CPP_EXPLICIT_H__
#define __PS3DK_CELL_GCM_COMMAND_CPP_EXPLICIT_H__

#ifdef __cplusplus

namespace cell { namespace Gcm {

struct CellGcmContext : public CellGcmContextData
{
    void CgUploadInternalConsts(CGprogram prog)
    { ::cellGcmCgUploadInternalConsts(this, prog); }
    void Finish(uint32_t ref)
    { ::cellGcmFinish(this, ref); }
    void FinishUnsafe(uint32_t ref)
    { ::cellGcmFinishUnsafe(this, ref); }
    void Flush()
    { ::cellGcmFlush(this); }
    void FlushUnsafe()
    { ::cellGcmFlushUnsafe(this); }
    void SetAlphaFunc(uint32_t func, uint32_t ref)
    { ::cellGcmSetAlphaFunc(this, func, ref); }
    void SetAlphaTestEnable(uint32_t enable)
    { ::cellGcmSetAlphaTestEnable(this, enable); }
    void SetAntiAliasingControl(uint32_t enable, uint32_t alphaToCoverage, uint32_t alphaToOne, uint32_t sampleMask)
    { ::cellGcmSetAntiAliasingControl(this, enable, alphaToCoverage, alphaToOne, sampleMask); }
    void SetBackPolygonMode(uint32_t mode)
    { ::cellGcmSetBackPolygonMode(this, mode); }
    void SetBackStencilFunc(uint32_t func, int32_t ref, uint32_t mask)
    { ::cellGcmSetBackStencilFunc(this, func, ref, mask); }
    void SetBackStencilMask(uint32_t mask)
    { ::cellGcmSetBackStencilMask(this, mask); }
    void SetBackStencilOp(uint32_t fail, uint32_t zfail, uint32_t zpass)
    { ::cellGcmSetBackStencilOp(this, fail, zfail, zpass); }
    void SetBlendColor(uint32_t color0, uint32_t color1)
    { ::cellGcmSetBlendColor(this, color0, color1); }
    void SetBlendEnable(uint32_t enable)
    { ::cellGcmSetBlendEnable(this, enable); }
    void SetBlendEquation(uint16_t color, uint16_t alpha)
    { ::cellGcmSetBlendEquation(this, color, alpha); }
    void SetBlendFunc(uint16_t sfcolor, uint16_t dfcolor, uint16_t sfalpha, uint16_t dfalpha)
    { ::cellGcmSetBlendFunc(this, sfcolor, dfcolor, sfalpha, dfalpha); }
    void SetCallCommand(uint32_t offset)
    { ::cellGcmSetCallCommand(this, offset); }
    void SetClearColor(uint32_t color)
    { ::cellGcmSetClearColor(this, color); }
    void SetClearDepthStencil(uint32_t value)
    { ::cellGcmSetClearDepthStencil(this, value); }
    void SetClearReport(uint8_t type)
    { ::cellGcmSetClearReport(this, type); }
    void SetClearSurface(uint32_t mask)
    { ::cellGcmSetClearSurface(this, mask); }
    void SetClearZcullSurface(uint32_t depth, uint32_t stencil)
    { ::cellGcmSetClearZcullSurface(this, depth, stencil); }
    void SetColorMask(uint32_t mask)
    { ::cellGcmSetColorMask(this, mask); }
    void SetColorMaskMrt(uint32_t mask)
    { ::cellGcmSetColorMaskMrt(this, mask); }
    void SetCullFace(uint32_t cfm)
    { ::cellGcmSetCullFace(this, cfm); }
    void SetCullFaceEnable(uint32_t enable)
    { ::cellGcmSetCullFaceEnable(this, enable); }
    void SetDepthBounds(float zMin, float zMax)
    { ::cellGcmSetDepthBounds(this, zMin, zMax); }
    void SetDepthBoundsTestEnable(uint32_t enable)
    { ::cellGcmSetDepthBoundsTestEnable(this, enable); }
    void SetDepthFunc(uint32_t func)
    { ::cellGcmSetDepthFunc(this, func); }
    void SetDepthMask(uint32_t mask)
    { ::cellGcmSetDepthMask(this, mask); }
    void SetDepthTestEnable(uint32_t enable)
    { ::cellGcmSetDepthTestEnable(this, enable); }
    void SetDitherEnable(uint32_t enable)
    { ::cellGcmSetDitherEnable(this, enable); }
    void SetDrawArrays(uint32_t type, uint32_t start, uint32_t count)
    { ::cellGcmSetDrawArrays(this, type, start, count); }
    void SetDrawBegin(uint32_t type)
    { ::cellGcmSetDrawBegin(this, type); }
    void SetDrawEnd()
    { ::cellGcmSetDrawEnd(this); }
    void SetDrawIndexArray(uint8_t mode, uint32_t count, uint8_t type, uint8_t location, uint32_t indicies)
    { ::cellGcmSetDrawIndexArray(this, mode, count, type, location, indicies); }
    int32_t SetFlip(uint8_t id)
    { return ::cellGcmSetFlip(this, id); }
    void SetFogMode(uint32_t mode)
    { ::cellGcmSetFogMode(this, mode); }
    void SetFogParams(float p0, float p1)
    { ::cellGcmSetFogParams(this, p0, p1); }
    void SetFragmentProgram(CGprogram prog, uint32_t offset)
    { ::cellGcmSetFragmentProgram(this, prog, offset); }
    void SetFragmentProgramGammaEnable(uint32_t enable)
    { ::cellGcmSetFragmentProgramGammaEnable(this, enable); }
    void SetFragmentProgramParameter(CGprogram prog, CGparameter param, const float *values, uint32_t addrOffset)
    { ::cellGcmSetFragmentProgramParameter(this, prog, param, values, addrOffset); }
    void SetFrequencyDividerOperation(uint16_t op)
    { ::cellGcmSetFrequencyDividerOperation(this, op); }
    void SetFrontFace(uint32_t dir)
    { ::cellGcmSetFrontFace(this, dir); }
    void SetFrontPolygonMode(uint32_t mode)
    { ::cellGcmSetFrontPolygonMode(this, mode); }
    void SetInvalidateTextureCache(uint32_t type)
    { ::cellGcmSetInvalidateTextureCache(this, type); }
    void SetInvalidateVertexCache()
    { ::cellGcmSetInvalidateVertexCache(this); }
    void SetInvalidateZcull()
    { ::cellGcmSetInvalidateZcull(this); }
    void SetJumpCommand(uint32_t offset)
    { ::cellGcmSetJumpCommand(this, offset); }
    void SetLogicOp(uint32_t op)
    { ::cellGcmSetLogicOp(this, op); }
    void SetLogicOpEnable(uint32_t enable)
    { ::cellGcmSetLogicOpEnable(this, enable); }
    void SetNopCommand(uint32_t count)
    { ::cellGcmSetNopCommand(this, count); }
    void SetPolySmoothEnable(uint32_t enable)
    { ::cellGcmSetPolySmoothEnable(this, enable); }
    void SetPolygonOffset(float factor, float units)
    { ::cellGcmSetPolygonOffset(this, factor, units); }
    void SetPolygonOffsetFillEnable(uint32_t enable)
    { ::cellGcmSetPolygonOffsetFillEnable(this, enable); }
    uint32_t SetPrepareFlip(uint8_t id)
    { return ::cellGcmSetPrepareFlip(this, id); }
    void SetReferenceCommand(uint32_t ref)
    { ::cellGcmSetReferenceCommand(this, ref); }
    void SetRenderEnable(uint32_t enable, uint32_t offset)
    { ::cellGcmSetRenderEnable(this, enable, offset); }
    void SetReport(uint8_t type, uint32_t index)
    { ::cellGcmSetReport(this, type, index); }
    void SetReportLocation(uint32_t location)
    { ::cellGcmSetReportLocation(this, location); }
    void SetReturnCommand()
    { ::cellGcmSetReturnCommand(this); }
    void SetScissor(uint16_t x, uint16_t y, uint16_t w, uint16_t h)
    { ::cellGcmSetScissor(this, x, y, w, h); }
    void SetScullControl(uint16_t func, uint8_t ref, uint8_t mask)
    { ::cellGcmSetScullControl(this, func, ref, mask); }
    void SetShadeMode(uint32_t mode)
    { ::cellGcmSetShadeMode(this, mode); }
    void SetShadeModel(uint32_t model)
    { ::cellGcmSetShadeModel(this, model); }
    void SetStencilFunc(uint32_t func, int32_t ref, uint32_t mask)
    { ::cellGcmSetStencilFunc(this, func, ref, mask); }
    void SetStencilMask(uint32_t mask)
    { ::cellGcmSetStencilMask(this, mask); }
    void SetStencilOp(uint32_t fail, uint32_t zfail, uint32_t zpass)
    { ::cellGcmSetStencilOp(this, fail, zfail, zpass); }
    void SetStencilTestEnable(uint32_t enable)
    { ::cellGcmSetStencilTestEnable(this, enable); }
    void SetSurface(const CellGcmSurface *surface)
    { ::cellGcmSetSurface(this, surface); }
    void SetTexture(uint8_t index, const CellGcmTexture *texture)
    { ::cellGcmSetTexture(this, index, texture); }
    void SetTextureAddress(uint8_t index, uint8_t wraps, uint8_t wrapt, uint8_t wrapr, uint8_t unsignedRemap, uint8_t zfunc, uint8_t gamma)
    { ::cellGcmSetTextureAddress(this, index, wraps, wrapt, wrapr, unsignedRemap, zfunc, gamma); }
    void SetTextureBorderColor(uint8_t index, uint32_t color)
    { ::cellGcmSetTextureBorderColor(this, index, color); }
    void SetTextureControl(uint8_t index, uint32_t enable, uint16_t minlod, uint16_t maxlod, uint8_t maxaniso)
    { ::cellGcmSetTextureControl(this, index, enable, minlod, maxlod, maxaniso); }
    void SetTextureFilter(uint8_t index, uint16_t bias, uint8_t min, uint8_t mag, uint8_t conv)
    { ::cellGcmSetTextureFilter(this, index, bias, min, mag, conv); }
    void SetTimeStamp(uint32_t index)
    { ::cellGcmSetTimeStamp(this, index); }
    void SetTransferData(uint8_t mode, uint32_t dst, uint32_t outpitch, uint32_t src, uint32_t inpitch, uint32_t linelength, uint32_t linecount)
    { ::cellGcmSetTransferData(this, mode, dst, outpitch, src, inpitch, linelength, linecount); }
    void SetTransferDataFormat(int32_t inpitch, int32_t outpitch, uint32_t linelength, uint32_t linecount, uint8_t inbytes, uint8_t outbytes)
    { ::cellGcmSetTransferDataFormat(this, inpitch, outpitch, linelength, linecount, inbytes, outbytes); }
    void SetTransferDataMode(uint8_t mode)
    { ::cellGcmSetTransferDataMode(this, mode); }
    void SetTransferDataOffset(uint32_t dst, uint32_t src)
    { ::cellGcmSetTransferDataOffset(this, dst, src); }
    void SetTransferImage(uint8_t mode, uint32_t dstOffset, uint32_t dstPitch, uint32_t dstX, uint32_t dstY, uint32_t srcOffset, uint32_t srcPitch, uint32_t srcX, uint32_t srcY, uint32_t width, uint32_t height, uint32_t bytesPerPixel)
    { ::cellGcmSetTransferImage(this, mode, dstOffset, dstPitch, dstX, dstY, srcOffset, srcPitch, srcX, srcY, width, height, bytesPerPixel); }
    void SetTransferScaleMode(uint8_t mode, uint8_t surface)
    { ::cellGcmSetTransferScaleMode(this, mode, surface); }
    void SetTransferScaleSurface(const gcmTransferScale *scale, const gcmTransferSurface *surface)
    { ::cellGcmSetTransferScaleSurface(this, scale, surface); }
    void SetTransferScaleSwizzle(const gcmTransferScale *scale, const gcmTransferSwizzle *swizzle)
    { ::cellGcmSetTransferScaleSwizzle(this, scale, swizzle); }
    void SetTwoSidedStencilTestEnable(uint32_t enable)
    { ::cellGcmSetTwoSidedStencilTestEnable(this, enable); }
    void SetUpdateFragmentProgramParameter(uint32_t offset)
    { ::cellGcmSetUpdateFragmentProgramParameter(this, offset); }
    void SetUserClipPlaneControl(uint32_t plane0, uint32_t plane1, uint32_t plane2, uint32_t plane3, uint32_t plane4, uint32_t plane5)
    { ::cellGcmSetUserClipPlaneControl(this, plane0, plane1, plane2, plane3, plane4, plane5); }
    void SetVertexAttribInputMask(uint16_t mask)
    { ::cellGcmSetVertexAttribInputMask(this, mask); }
    void SetVertexAttribOutputMask(uint32_t mask)
    { ::cellGcmSetVertexAttribOutputMask(this, mask); }
    void SetVertexData4f(uint8_t index, const float v[4])
    { ::cellGcmSetVertexData4f(this, index, v); }
    void SetVertexDataArray(uint8_t index, uint16_t frequency, uint8_t stride, uint8_t size, uint8_t type, uint8_t location, uint32_t offset)
    { ::cellGcmSetVertexDataArray(this, index, frequency, stride, size, type, location, offset); }
    void SetVertexProgram(CGprogram prog, void *ucode)
    { ::cellGcmSetVertexProgram(this, prog, ucode); }
    void SetVertexProgramConstants(uint32_t start, uint32_t count, const float *data)
    { ::cellGcmSetVertexProgramConstants(this, start, count, data); }
    void SetVertexProgramParameter(CGparameter param, const float *values)
    { ::cellGcmSetVertexProgramParameter(this, param, values); }
    void SetVertexProgramParameterBlock(uint32_t baseConst, uint32_t constCount, const float *values)
    { ::cellGcmSetVertexProgramParameterBlock(this, baseConst, constCount, values); }
    void SetViewport(uint16_t x, uint16_t y, uint16_t w, uint16_t h, float min_z, float max_z, const float scale[4], const float offset[4])
    { ::cellGcmSetViewport(this, x, y, w, h, min_z, max_z, scale, offset); }
    void SetWaitFlip()
    { ::cellGcmSetWaitFlip(this); }
    void SetWaitLabel(uint8_t index, uint32_t value)
    { ::cellGcmSetWaitLabel(this, index, value); }
    void SetWriteBackEndLabel(uint8_t index, uint32_t value)
    { ::cellGcmSetWriteBackEndLabel(this, index, value); }
    void SetWriteCommandLabel(uint8_t index, uint32_t value)
    { ::cellGcmSetWriteCommandLabel(this, index, value); }
    void SetWriteTextureLabel(uint8_t index, uint32_t value)
    { ::cellGcmSetWriteTextureLabel(this, index, value); }
    void SetZMinMaxControl(uint32_t cullNearFarEnable, uint32_t zclampEnable, uint32_t cullIgnoreW)
    { ::cellGcmSetZMinMaxControl(this, cullNearFarEnable, zclampEnable, cullIgnoreW); }
    void SetZcullControl(uint8_t cullDir, uint8_t cullFmt)
    { ::cellGcmSetZcullControl(this, cullDir, cullFmt); }
    void SetZcullEnable(uint32_t depth, uint32_t stencil)
    { ::cellGcmSetZcullEnable(this, depth, stencil); }
    void SetZcullLimit(uint16_t moveForwardLimit, uint16_t pushBackLimit)
    { ::cellGcmSetZcullLimit(this, moveForwardLimit, pushBackLimit); }
    void SetZcullStatsEnable(uint32_t enable)
    { ::cellGcmSetZcullStatsEnable(this, enable); }
    void SetZpassPixelCountEnable(uint32_t enable)
    { ::cellGcmSetZpassPixelCountEnable(this, enable); }
};

} }   /* namespace cell::Gcm */

#endif /* __cplusplus */

#endif /* __PS3DK_CELL_GCM_COMMAND_CPP_EXPLICIT_H__ */
