/*! \file cell/gcm/gcm_command_c.h
 \brief Sony-SDK-source-compat libgcm command-emitter forwarders.

  Phase 7 step 3.  Maps the most-used Sony cellGcmSet/cellGcmFlush/
  cellGcmFinish command emitters to PSL1GHT's rsx equivalents in
  librsx.  Sony's command-emitter family is generated by macro from
  <cell/gcm/gcm_prototypes_sub.h> in 6 variants (Safe/Unsafe x
  Inline/Outline x Run/Measure); we only ship the safe/outline variant
  here since that's what user source actually calls.

  Function signatures match Sony exactly: each takes
  `CellGcmContextData *thisContext` as first arg (== gcmContextData *,
  byte-identical alias from <cell/gcm.h>), then the GPU command args.

  Covered (~25 functions):
    Sync         Flush / Finish / SetReferenceCommand
    Surface      SetSurface / SetClearSurface / SetClearColor /
                 SetClearDepthStencil
    Labels       SetWaitLabel / SetWriteCommandLabel /
                 SetWriteBackEndLabel / SetWriteTextureLabel
    State        SetColorMask / SetColorMaskMrt / SetDepthFunc /
                 SetDepthTestEnable / SetDepthMask /
                 SetBlendEnable / SetShadeModel
    Geometry     SetViewport / SetCullFace / SetFrontFace /
                 SetCullFaceEnable / SetUserClipPlaneControl

  Deferred (massive surface, mostly draw/texture/vertex-program):
    cellGcmSetVertexProgram / SetFragmentProgram / SetVertexDataArray /
    SetDrawArrays / SetDrawIndexArray / SetTexture / SetTextureControl /
    SetTextureFilter / SetTransferImage / SetTransferData / etc.
    These bind to PSL1GHT's rsxSetVertexProgram / etc. — same forwarder
    pattern, just larger surface.

  Note Sony spelling of "BackEnd" with capital E (vs PSL1GHT's
  "Backend") — preserved exactly so Sony source compiles.
*/

#ifndef __PSL1GHT_CELL_GCM_COMMAND_C_H__
#define __PSL1GHT_CELL_GCM_COMMAND_C_H__

#include <stdint.h>
#include <ppu-types.h>
#include <rsx/gcm_sys.h>
#include <rsx/commands.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CellGcmContextData / CellGcmConfig come from <cell/gcm.h>; this
 * header is normally included transitively from there.  For direct
 * inclusion, the typedef is brought in by rsx/gcm_sys.h via
 * gcmContextData (CellGcmContextData is its alias). */

/* ==========================================================
 * Sync
 * ========================================================== */

static inline void cellGcmFlush(CellGcmContextData *thisContext)
{
	rsxFlushBuffer(thisContext);
}

static inline void cellGcmFlushUnsafe(CellGcmContextData *thisContext)
{
	rsxFlushBufferUnsafe(thisContext);
}

static inline void cellGcmFinish(CellGcmContextData *thisContext, uint32_t ref)
{
	rsxFinish(thisContext, ref);
}

static inline void cellGcmFinishUnsafe(CellGcmContextData *thisContext, uint32_t ref)
{
	rsxFinishUnsafe(thisContext, ref);
}

static inline void cellGcmSetReferenceCommand(CellGcmContextData *thisContext, uint32_t ref)
{
	rsxSetReferenceCommand(thisContext, ref);
}

/* ==========================================================
 * Surface / clear
 * ========================================================== */

static inline void cellGcmSetSurface(CellGcmContextData *thisContext, const CellGcmSurface *surface)
{
	rsxSetSurface(thisContext, (const gcmSurface *)surface);
}

static inline void cellGcmSetClearColor(CellGcmContextData *thisContext, uint32_t color)
{
	rsxSetClearColor(thisContext, color);
}

static inline void cellGcmSetClearDepthStencil(CellGcmContextData *thisContext, uint32_t value)
{
	rsxSetClearDepthStencil(thisContext, value);
}

static inline void cellGcmSetClearSurface(CellGcmContextData *thisContext, uint32_t mask)
{
	rsxClearSurface(thisContext, mask);
}

/* ==========================================================
 * Labels (fence-style sync points in the command stream)
 * ========================================================== */

static inline void cellGcmSetWaitLabel(CellGcmContextData *thisContext, uint8_t index, uint32_t value)
{
	rsxSetWaitLabel(thisContext, index, value);
}

static inline void cellGcmSetWriteCommandLabel(CellGcmContextData *thisContext, uint8_t index, uint32_t value)
{
	rsxSetWriteCommandLabel(thisContext, index, value);
}

/* Note Sony spelling: BackEnd (capital E) vs PSL1GHT's Backend. */
static inline void cellGcmSetWriteBackEndLabel(CellGcmContextData *thisContext, uint8_t index, uint32_t value)
{
	rsxSetWriteBackendLabel(thisContext, index, value);
}

static inline void cellGcmSetWriteTextureLabel(CellGcmContextData *thisContext, uint8_t index, uint32_t value)
{
	rsxSetWriteTextureLabel(thisContext, index, value);
}

/* ==========================================================
 * Color / depth state
 * ========================================================== */

static inline void cellGcmSetColorMask(CellGcmContextData *thisContext, uint32_t mask)
{
	rsxSetColorMask(thisContext, mask);
}

static inline void cellGcmSetColorMaskMrt(CellGcmContextData *thisContext, uint32_t mask)
{
	rsxSetColorMaskMrt(thisContext, mask);
}

static inline void cellGcmSetDepthFunc(CellGcmContextData *thisContext, uint32_t func)
{
	rsxSetDepthFunc(thisContext, func);
}

static inline void cellGcmSetDepthTestEnable(CellGcmContextData *thisContext, uint32_t enable)
{
	rsxSetDepthTestEnable(thisContext, enable);
}

static inline void cellGcmSetDepthMask(CellGcmContextData *thisContext, uint32_t mask)
{
	rsxSetDepthWriteEnable(thisContext, mask);
}

static inline void cellGcmSetBlendEnable(CellGcmContextData *thisContext, uint32_t enable)
{
	rsxSetBlendEnable(thisContext, enable);
}

static inline void cellGcmSetShadeModel(CellGcmContextData *thisContext, uint32_t model)
{
	rsxSetShadeModel(thisContext, model);
}

/* ==========================================================
 * Geometry / viewport / culling
 * ========================================================== */

static inline void cellGcmSetViewport(CellGcmContextData *thisContext,
                                      uint16_t x, uint16_t y, uint16_t w, uint16_t h,
                                      float min_z, float max_z,
                                      const float scale[4], const float offset[4])
{
	rsxSetViewport(thisContext, x, y, w, h, min_z, max_z, scale, offset);
}

static inline void cellGcmSetCullFace(CellGcmContextData *thisContext, uint32_t cfm)
{
	rsxSetCullFace(thisContext, cfm);
}

static inline void cellGcmSetFrontFace(CellGcmContextData *thisContext, uint32_t dir)
{
	rsxSetFrontFace(thisContext, dir);
}

static inline void cellGcmSetCullFaceEnable(CellGcmContextData *thisContext, uint32_t enable)
{
	rsxSetCullFaceEnable(thisContext, enable);
}

static inline void cellGcmSetUserClipPlaneControl(CellGcmContextData *thisContext,
                                                  uint32_t plane0, uint32_t plane1,
                                                  uint32_t plane2, uint32_t plane3,
                                                  uint32_t plane4, uint32_t plane5)
{
	rsxSetUserClipPlaneControl(thisContext, plane0, plane1, plane2, plane3, plane4, plane5);
}

/* ==========================================================
 * Step 4b: Draw / vertex-data / texture / transfer / cache
 *
 * Bulk forwarders for Sony's draw and texture command emitters.
 * Cg-handle-using variants (cellGcmSetVertexProgram(CGprogram, ...)
 * etc.) are deliberately not here — they need a Cg-runtime bridge
 * layer over PSL1GHT's rsxVertexProgram / rsxFragmentProgram structs
 * which is a separate undertaking.  These below take only POD args
 * and forward 1:1 to PSL1GHT's rsx* family.
 * ========================================================== */

/* --- Draw --- */

static inline void cellGcmSetDrawArrays(CellGcmContextData *thisContext,
                                        uint32_t type, uint32_t start, uint32_t count)
{
	rsxDrawVertexArray(thisContext, type, start, count);
}

static inline void cellGcmSetDrawIndexArray(CellGcmContextData *thisContext,
                                            uint8_t type, uint32_t offset, uint32_t count,
                                            uint8_t data_type, uint8_t location)
{
	rsxDrawIndexArray(thisContext, type, offset, count, data_type, location);
}

static inline void cellGcmSetDrawBegin(CellGcmContextData *thisContext, uint32_t type)
{
	rsxDrawVertexBegin(thisContext, type);
}

static inline void cellGcmSetDrawEnd(CellGcmContextData *thisContext)
{
	rsxDrawVertexEnd(thisContext);
}

/* --- Vertex data (per-attribute) --- */

static inline void cellGcmSetVertexData4f(CellGcmContextData *thisContext,
                                          uint8_t index, const float v[4])
{
	rsxDrawVertex4f(thisContext, index, v);
}

static inline void cellGcmSetVertexDataArray(CellGcmContextData *thisContext,
                                             uint8_t index, uint16_t frequency,
                                             uint8_t stride, uint8_t size,
                                             uint8_t type, uint8_t location,
                                             uint32_t offset)
{
	/* Sony and PSL1GHT agree on the param set but order args differently.
	 * Sony: (index, freq, stride, size, type, location, offset)
	 * PSL1GHT: (attr, freq, offset, stride, elems, dtype, location) */
	rsxBindVertexArrayAttrib(thisContext, index, frequency, offset,
	                         stride, size, type, location);
}

static inline void cellGcmSetVertexAttribInputMask(CellGcmContextData *thisContext, uint16_t mask)
{
	(void)thisContext; (void)mask;
	/* PSL1GHT doesn't expose this directly; hardware default is to derive
	 * it from rsxBindVertexArrayAttrib calls.  Stub for source-compat. */
}

static inline void cellGcmSetVertexAttribOutputMask(CellGcmContextData *thisContext, uint32_t mask)
{
	rsxSetVertexAttribOutputMask(thisContext, mask);
}

/* --- Vertex program constants (no Cg handle needed) --- */

static inline void cellGcmSetVertexProgramConstants(CellGcmContextData *thisContext,
                                                    uint32_t start, uint32_t count,
                                                    const float *data)
{
	rsxSetVertexProgramConstants(thisContext, start, count, data);
}

/* --- Fragment program flags --- */

static inline void cellGcmSetFragmentProgramGammaEnable(CellGcmContextData *thisContext,
                                                        uint32_t enable)
{
	rsxSetFragmentProgramGammaEnable(thisContext, enable);
}

/* --- Texture cache invalidation --- */

static inline void cellGcmSetInvalidateVertexCache(CellGcmContextData *thisContext)
{
	rsxInvalidateVertexCache(thisContext);
}

static inline void cellGcmSetInvalidateTextureCache(CellGcmContextData *thisContext, uint32_t type)
{
	rsxInvalidateTextureCache(thisContext, type);
}

/* --- 2D transfer engine (BLT path; no shaders required) --- */

static inline void cellGcmSetTransferDataMode(CellGcmContextData *thisContext, uint8_t mode)
{
	rsxSetTransferDataMode(thisContext, mode);
}

static inline void cellGcmSetTransferDataOffset(CellGcmContextData *thisContext,
                                                uint32_t dst, uint32_t src)
{
	rsxSetTransferDataOffset(thisContext, dst, src);
}

static inline void cellGcmSetTransferDataFormat(CellGcmContextData *thisContext,
                                                int32_t inpitch, int32_t outpitch,
                                                uint32_t linelength, uint32_t linecount,
                                                uint8_t inbytes, uint8_t outbytes)
{
	rsxSetTransferDataFormat(thisContext, inpitch, outpitch,
	                         linelength, linecount, inbytes, outbytes);
}

static inline void cellGcmSetTransferData(CellGcmContextData *thisContext,
                                          uint8_t mode, uint32_t dst, uint32_t outpitch,
                                          uint32_t src, uint32_t inpitch,
                                          uint32_t linelength, uint32_t linecount)
{
	rsxSetTransferData(thisContext, mode, dst, outpitch, src,
	                   inpitch, linelength, linecount);
}

static inline void cellGcmSetTransferImage(CellGcmContextData *thisContext,
                                           uint8_t mode,
                                           uint32_t dstOffset, uint32_t dstPitch,
                                           uint32_t dstX, uint32_t dstY,
                                           uint32_t srcOffset, uint32_t srcPitch,
                                           uint32_t srcX, uint32_t srcY,
                                           uint32_t width, uint32_t height,
                                           uint32_t bytesPerPixel)
{
	rsxSetTransferImage(thisContext, mode,
	                    dstOffset, dstPitch, dstX, dstY,
	                    srcOffset, srcPitch, srcX, srcY,
	                    width, height, bytesPerPixel);
}

#ifdef __cplusplus
}
#endif

#endif /* __PSL1GHT_CELL_GCM_COMMAND_C_H__ */
