/* cell/usbd/error.h - libusbd error codes.
 *
 * Clean-room header.  CELL_USBD_ERROR_* constants encode the
 * module-relative error numbers the cell SDK ABI requires.
 */
#ifndef __PS3DK_CELL_USBD_ERROR_H__
#define __PS3DK_CELL_USBD_ERROR_H__

#include <cell/error.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * CELL_ERROR_FACILITY_USB = 0x011
 * libusbd range: 0x8011_0001 – 0x8011_00ff
 */

#define CELL_USBD_MAKE_ERROR(status) \
    CELL_ERROR_MAKE_ERROR(CELL_ERROR_FACILITY_USB, status)

#define CELL_USBD_ERROR_NOT_INITIALIZED         CELL_ERROR_CAST(0x80110001)
#define CELL_USBD_ERROR_ALREADY_INITIALIZED     CELL_ERROR_CAST(0x80110002)
#define CELL_USBD_ERROR_NO_MEMORY               CELL_ERROR_CAST(0x80110003)
#define CELL_USBD_ERROR_INVALID_PARAM           CELL_ERROR_CAST(0x80110004)
#define CELL_USBD_ERROR_INVALID_TRANSFER_TYPE   CELL_ERROR_CAST(0x80110005)
#define CELL_USBD_ERROR_LDD_ALREADY_REGISTERED  CELL_ERROR_CAST(0x80110006)
#define CELL_USBD_ERROR_LDD_NOT_ALLOCATED       CELL_ERROR_CAST(0x80110007)
#define CELL_USBD_ERROR_LDD_NOT_RELEASED        CELL_ERROR_CAST(0x80110008)
#define CELL_USBD_ERROR_LDD_NOT_FOUND           CELL_ERROR_CAST(0x80110009)
#define CELL_USBD_ERROR_DEVICE_NOT_FOUND        CELL_ERROR_CAST(0x8011000a)
#define CELL_USBD_ERROR_PIPE_NOT_ALLOCATED      CELL_ERROR_CAST(0x8011000b)
#define CELL_USBD_ERROR_PIPE_NOT_RELEASED       CELL_ERROR_CAST(0x8011000c)
#define CELL_USBD_ERROR_PIPE_NOT_FOUND          CELL_ERROR_CAST(0x8011000d)
#define CELL_USBD_ERROR_IOREQ_NOT_ALLOCATED     CELL_ERROR_CAST(0x8011000e)
#define CELL_USBD_ERROR_IOREQ_NOT_RELEASED      CELL_ERROR_CAST(0x8011000f)
#define CELL_USBD_ERROR_IOREQ_NOT_FOUND         CELL_ERROR_CAST(0x80110010)
#define CELL_USBD_ERROR_CANNOT_GET_DESCRIPTOR   CELL_ERROR_CAST(0x80110011)
#define CELL_USBD_ERROR_FATAL                   CELL_ERROR_CAST(0x801100ff)

#ifdef __cplusplus
}
#endif

#endif /* __PS3DK_CELL_USBD_ERROR_H__ */
