void main(float4 c : TEXCOORD0, out float4 o : COLOR)
{
    float s0 = step(0.01, c.x + c.y * 0.001);
    float s1 = step(0.02, c.x + c.y * 0.001);
    float s2 = step(0.03, c.x + c.y * 0.001);
    float s3 = step(0.04, c.x + c.y * 0.001);
    float s4 = step(0.05, c.x + c.y * 0.001);
    float s5 = step(0.06, c.x + c.y * 0.001);
    float s6 = step(0.07, c.x + c.y * 0.001);
    float s7 = step(0.08, c.x + c.y * 0.001);
    float v = (s0 + s1 + s2 + s3 + s4 + s5 + s6 + s7) * 0.125000;
    o = float4(v, v, v, 1.0);
}
