[package]
name = "sfo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "PARAM.SFO parser, writer, and editor"

[lib]
name = "sfo"
path = "src/lib.rs"

[[bin]]
name = "sfo-editor"
path = "src/main.rs"

[[bin]]
name = "sfo-editor-gui"
path = "src/gui_main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
eframe = { version = "0.29.1", default-features = false, features = ["glow", "default_fonts"] }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
