/* cell/sail/common.h — cellSail shared types, enums, and error codes.
   Clean-room header.  PRXPTR-free (no cross-SPRX structs in this file). */
#ifndef __PS3DK_CELL_SAIL_COMMON_H__
#define __PS3DK_CELL_SAIL_COMMON_H__
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <cell/error.h>
#ifdef __PPU__
#include <ppu-types.h>
#else
#ifndef ATTRIBUTE_PRXPTR
#define ATTRIBUTE_PRXPTR
#endif
#endif
#ifdef __cplusplus
extern "C" {
#endif
/* error codes 0x8061_0700 – 0x8061_07FF */
#define CELL_SAIL_ERROR_INVALID_ARG        CELL_ERROR_CAST(0x80610701)
#define CELL_SAIL_ERROR_INVALID_STATE      CELL_ERROR_CAST(0x80610702)
#define CELL_SAIL_ERROR_UNSUPPORTED_STREAM CELL_ERROR_CAST(0x80610703)
#define CELL_SAIL_ERROR_INDEX_OUT_OF_RANGE CELL_ERROR_CAST(0x80610704)
#define CELL_SAIL_ERROR_EMPTY              CELL_ERROR_CAST(0x80610705)
#define CELL_SAIL_ERROR_FULLED             CELL_ERROR_CAST(0x80610706)
#define CELL_SAIL_ERROR_USING              CELL_ERROR_CAST(0x80610707)
#define CELL_SAIL_ERROR_NOT_AVAILABLE      CELL_ERROR_CAST(0x80610708)
#define CELL_SAIL_ERROR_CANCEL             CELL_ERROR_CAST(0x80610709)
#define CELL_SAIL_ERROR_MEMORY             CELL_ERROR_CAST(0x806107F0)
#define CELL_SAIL_ERROR_INVALID_FD         CELL_ERROR_CAST(0x806107F1)
#define CELL_SAIL_ERROR_FATAL              CELL_ERROR_CAST(0x806107FF)

#define CELL_SAIL_4CC(a,b,c,d) ((uint32_t)(a)|((uint32_t)(b)<<8)|((uint32_t)(c)<<16)|((uint32_t)(d)<<24))

typedef enum { CELL_SAIL_EVENT_EMPTY=0, CELL_SAIL_EVENT_ERROR_OCCURED=1, CELL_SAIL_EVENT_PLAYER_CALL_COMPLETED=2, CELL_SAIL_EVENT_PLAYER_STATE_CHANGED=3, CELL_SAIL_EVENT_STREAM_OPENED=4, CELL_SAIL_EVENT_STREAM_CLOSED=5, CELL_SAIL_EVENT_SESSION_STARTED=6, CELL_SAIL_EVENT_PAUSE_STATE_CHANGED=7, CELL_SAIL_EVENT_SOURCE_EOS=8, CELL_SAIL_EVENT_ES_OPENED=9, CELL_SAIL_EVENT_ES_CLOSED=10, CELL_SAIL_EVENT_MEDIA_STATE_CHANGED=11 } CellSailEventType;
typedef union { struct { uint32_t major, minor; } u32x2; struct { uint64_t value; } u64; } CellSailEvent;
typedef enum { CELL_SAIL_STREAM_PAMF=0, CELL_SAIL_STREAM_MP4=1, CELL_SAIL_STREAM_AVI=2, CELL_SAIL_STREAM_USER_DEFINED_0=3, CELL_SAIL_STREAM_UNSPECIFIED=-1 } CellSailStreamType;
enum { CELL_SAIL_ES_AUDIO=0, CELL_SAIL_ES_VIDEO=1, CELL_SAIL_ES_USER=2 };

/* audio */
enum { CELL_SAIL_AUDIO_CODING_UNSPECIFIED=-1, CELL_SAIL_AUDIO_CODING_LPCM_FLOAT32=1 };
enum { CELL_SAIL_AUDIO_CHNUM_UNSPECIFIED=-1, CELL_SAIL_AUDIO_AUSAMPLE_UNSPECIFIED=-1, CELL_SAIL_AUDIO_SAMPLE_NUM_UNSPECIFIED=-1 };
enum { CELL_SAIL_AUDIO_FS_32000HZ=32000, CELL_SAIL_AUDIO_FS_44100HZ=44100, CELL_SAIL_AUDIO_FS_48000HZ=48000, CELL_SAIL_AUDIO_FS_96000HZ=96000, CELL_SAIL_AUDIO_FS_88200HZ=88200, CELL_SAIL_AUDIO_FS_64000HZ=64000, CELL_SAIL_AUDIO_FS_24000HZ=24000, CELL_SAIL_AUDIO_FS_22050HZ=22050, CELL_SAIL_AUDIO_FS_16000HZ=16000, CELL_SAIL_AUDIO_FS_12000HZ=12000, CELL_SAIL_AUDIO_FS_11025HZ=11025, CELL_SAIL_AUDIO_FS_8000HZ=8000, CELL_SAIL_AUDIO_FS_7350HZ=7350, CELL_SAIL_AUDIO_FS_192000HZ=192000, CELL_SAIL_AUDIO_FS_UNSPECIFIED=-1 };
enum { CELL_SAIL_AUDIO_CH_LAYOUT_UNDEFINED=0, CELL_SAIL_AUDIO_CH_LAYOUT_1CH=1, CELL_SAIL_AUDIO_CH_LAYOUT_2CH_LR=2, CELL_SAIL_AUDIO_CH_LAYOUT_3CH_LCR=3, CELL_SAIL_AUDIO_CH_LAYOUT_3CH_LRc=4, CELL_SAIL_AUDIO_CH_LAYOUT_4CH_LCRc=5, CELL_SAIL_AUDIO_CH_LAYOUT_4CH_LRlr=6, CELL_SAIL_AUDIO_CH_LAYOUT_5CH_LCRlr=7, CELL_SAIL_AUDIO_CH_LAYOUT_6CH_LCRlrE=8, CELL_SAIL_AUDIO_CH_LAYOUT_6CH_LCRxyE=9, CELL_SAIL_AUDIO_CH_LAYOUT_7CH_LCRxycE=10, CELL_SAIL_AUDIO_CH_LAYOUT_8CH_LRCElrxy=11, CELL_SAIL_AUDIO_CH_LAYOUT_2CH_DUAL=12, CELL_SAIL_AUDIO_CH_LAYOUT_UNSPECIFIED=-1 };
typedef struct { int8_t coding, chNum; int16_t sampleNum; int32_t fs, chLayout, reserved0; int64_t reserved1; } CellSailAudioFormat;

/* video */
enum { CELL_SAIL_VIDEO_CODING_UNSPECIFIED=-1, CELL_SAIL_VIDEO_CODING_ARGB_INTERLEAVED=0, CELL_SAIL_VIDEO_CODING_RGBA_INTERLEAVED=1, CELL_SAIL_VIDEO_CODING_YUV422_U_Y0_V_Y1=2, CELL_SAIL_VIDEO_CODING_YUV420_PLANAR=3, CELL_SAIL_VIDEO_CODING_YUV422_Y0_U_Y1_V=4, CELL_SAIL_VIDEO_CODING_YUV422_V_Y1_U_Y0=9, CELL_SAIL_VIDEO_CODING_YUV422_Y1_V_Y0_U=10, CELL_SAIL_VIDEO_CODING_JPEG=11, CELL_SAIL_VIDEO_CODING_RAW8_BAYER_BGGR=12, CELL_SAIL_VIDEO_CODING_UYVY422_INTERLEAVED=2, CELL_SAIL_VIDEO_CODING_YUYV422_INTERLEAVED=4, CELL_SAIL_VIDEO_CODING_VYUY422_REVERSE_INTERLEAVED=9, CELL_SAIL_VIDEO_CODING_RAW8_BAYER_GRBG=12 };
enum { CELL_SAIL_VIDEO_COLOR_MATRIX_UNSPECIFIED=-1, CELL_SAIL_VIDEO_COLOR_MATRIX_BT601=0, CELL_SAIL_VIDEO_COLOR_MATRIX_BT709=1 };
enum { CELL_SAIL_VIDEO_SCAN_UNSPECIFIED=-1, CELL_SAIL_VIDEO_SCAN_PROGRESSIVE=0, CELL_SAIL_VIDEO_SCAN_INTERLACE=1 };
enum { CELL_SAIL_VIDEO_FRAME_RATE_UNSPECIFIED=-1, CELL_SAIL_VIDEO_FRAME_RATE_24000_1001HZ=0, CELL_SAIL_VIDEO_FRAME_RATE_24HZ=1, CELL_SAIL_VIDEO_FRAME_RATE_25HZ=2, CELL_SAIL_VIDEO_FRAME_RATE_30000_1001HZ=3, CELL_SAIL_VIDEO_FRAME_RATE_30HZ=4, CELL_SAIL_VIDEO_FRAME_RATE_50HZ=5, CELL_SAIL_VIDEO_FRAME_RATE_60000_1001HZ=6, CELL_SAIL_VIDEO_FRAME_RATE_60HZ=7 };
enum { CELL_SAIL_VIDEO_ASPECT_RATIO_UNSPECIFIED=-1, CELL_SAIL_VIDEO_ASPECT_RATIO_1_1=1, CELL_SAIL_VIDEO_ASPECT_RATIO_12_11=2, CELL_SAIL_VIDEO_ASPECT_RATIO_10_11=3, CELL_SAIL_VIDEO_ASPECT_RATIO_16_11=4, CELL_SAIL_VIDEO_ASPECT_RATIO_40_33=5, CELL_SAIL_VIDEO_ASPECT_RATIO_4_3=14 };
typedef struct { int8_t coding, scan; int16_t frameRate, aspectRatio; int32_t width, height, pitch, colorMatrix; int32_t alphaUsedFlag, reserved0; int64_t reserved1; } CellSailVideoFormat;

/* AU info + feeder frame info */
typedef struct { uint64_t pts, dts; uint32_t size; uint32_t reserved; } CellSailAuInfo;
typedef struct { uint64_t internalData[4]; } CellSailFeederFrameInfo;
typedef struct { uint64_t internalData[8]; } CellSailSourceBufferItem;

/* CellSailStartCommand forward-decl from source.h */
struct CellSailSourceStartCommand;
typedef struct CellSailSourceStartCommand CellSailStartCommand;

/* Memory allocator (root init) */
typedef void* (*CellSailMemAllocatorFuncAlloc)(void*,size_t,size_t);
typedef void  (*CellSailMemAllocatorFuncFree)(void*,size_t,void*);
typedef struct {
    CellSailMemAllocatorFuncAlloc pAlloc ATTRIBUTE_PRXPTR;
    CellSailMemAllocatorFuncFree  pFree  ATTRIBUTE_PRXPTR;
} CellSailMemAllocatorFuncs;
typedef struct {
    CellSailMemAllocatorFuncs callbacks;
    void *pArg ATTRIBUTE_PRXPTR;
} CellSailMemAllocator;
int cellSailMemAllocatorInitialize(CellSailMemAllocator*,const CellSailMemAllocatorFuncs*,void*);

#ifdef __cplusplus
}
#endif
#endif
