/*! \file cell/cell.h
 \brief Top-level umbrella header for the PS3 Custom Toolchain SDK.

  Including this header pulls in:
    - cell/sdk_version.h — PS3SDK_VERSION_* macros identifying the SDK
      build the consuming code is compiling against.

  This header intentionally stays small.  It is the canonical place to
  reach for the SDK version string at compile time:

      #include <cell/cell.h>
      printf("Built against SDK %s\n", PS3SDK_VERSION);

  cell/sdk_version.h is generated by `scripts/version.sh --format=header`
  during `make -C sdk install` and lives at $PS3DK/ppu/include/cell/.
*/

#ifndef __PS3SDK_CELL_CELL_H__
#define __PS3SDK_CELL_CELL_H__

#include <cell/sdk_version.h>

#endif /* __PS3SDK_CELL_CELL_H__ */
