/*! \file cell/gcm_pm.h
 \brief Cell-style libgcm performance monitor declaration surface.

  This header intentionally exposes only the API shape needed by source that
  includes <cell/gcm_pm.h>.  Per-domain hardware event IDs are not shipped here
  until they can be sourced through an independent public reference.
*/

#ifndef __PS3TC_CELL_GCM_PM_H__
#define __PS3TC_CELL_GCM_PM_H__

#include <stdint.h>
#include <cell/error.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum CellGcmPerfMonDomain {
    CELL_GCM_PM_DOMAIN_HCLK = 0,
    CELL_GCM_PM_DOMAIN_GCLK,
    CELL_GCM_PM_DOMAIN_RCLK,
    CELL_GCM_PM_DOMAIN_SCLK,
    CELL_GCM_PM_DOMAIN_MCLK,
    CELL_GCM_PM_DOMAIN_ICLK,
    CELL_GCM_PM_DOMAIN_NUM
} CellGcmPerfMonDomain;

typedef uint32_t CellGcmPerfMonHclk;
typedef uint32_t CellGcmPerfMonGclk;
typedef uint32_t CellGcmPerfMonRclk;
typedef uint32_t CellGcmPerfMonSclk;
typedef uint32_t CellGcmPerfMonMclk;
typedef uint32_t CellGcmPerfMonIclk;

enum {
    CELL_GCM_PM_MAX_EVENT = 4,
    CELL_GCM_PM_MAX_COUNTER = 4
};

#define CELL_GCM_ERROR_PM_STATE_INVALID CELL_ERROR_CAST(0x802100f1)

int32_t cellGcmInitPerfMon(void);
int32_t cellGcmExitPerfMon(void);
int32_t cellGcmSetPerfMonEvent(uint32_t domain,
                               const uint32_t event[CELL_GCM_PM_MAX_EVENT]);
int32_t cellGcmGetPerfMonCounter(uint32_t domain,
                                 uint32_t counter[CELL_GCM_PM_MAX_COUNTER],
                                 uint32_t *cycle);

#ifdef __cplusplus
}
#endif

/* Performance-monitor counter selectors (host, graphics, memory and shader clock domains). */
#define CELL_GCM_PM_HCLK_COMMAND_FEED                1
#define CELL_GCM_PM_HCLK_CELL_MASTER_LOCAL_MEM_READ  5
#define CELL_GCM_PM_HCLK_CELL_MASTER_LOCAL_MEM_WRITE_TOTAL 6
#define CELL_GCM_PM_HCLK_CELL_MASTER_LOCAL_MEM_WRITE_32BIT_PACKET 7
#define CELL_GCM_PM_HCLK_CELL_MASTER_LOCAL_MEM_WRITE_128BIT_PACKET 9
#define CELL_GCM_PM_HCLK_IOIF2HOST_READ_DATA         10
#define CELL_GCM_PM_HCLK_IOIF2HOST_WRITE_DATA        11
#define CELL_GCM_PM_GCLK_SETUP2RASTER_ACTIVE         2
#define CELL_GCM_PM_GCLK_SETUP2RASTER_IDLE           3
#define CELL_GCM_PM_GCLK_SETUP2RASTER_STALLING       4
#define CELL_GCM_PM_GCLK_SETUP2RASTER_STARVING       5
#define CELL_GCM_PM_GCLK_INSTRUCTION_ISSUED_VPE0     9
#define CELL_GCM_PM_GCLK_PRIMITIVECOUNT              20
#define CELL_GCM_PM_GCLK_CRASTER_OUTPUT_TILE_COUNT   23
#define CELL_GCM_PM_GCLK_CRASTER_SEARCH_MODE         24
#define CELL_GCM_PM_GCLK_IDX_GEOM_ATTRIBUTE_COUNT    39
#define CELL_GCM_PM_GCLK_IDX_VTX_CACHE_HIT           40
#define CELL_GCM_PM_GCLK_IDX_VTX_CACHE_MISS          41
#define CELL_GCM_PM_GCLK_SETUP_POINTS                44
#define CELL_GCM_PM_GCLK_SETUP_CULLS                 45
#define CELL_GCM_PM_GCLK_SETUP_LINES                 46
#define CELL_GCM_PM_GCLK_SETUP_TRIANGLES             47
#define CELL_GCM_PM_GCLK_VPC_CULL_PRIMITIVE          48
#define CELL_GCM_PM_GCLK_VPC_CULL_FRUSTUM            49
#define CELL_GCM_PM_GCLK_VPC_CULL_ZERO_AREA          50
#define CELL_GCM_PM_GCLK_VPC_CULL_BACKFACE           51
#define CELL_GCM_PM_GCLK_VPC_CULL_WOULD_CLIP         53
#define CELL_GCM_PM_GCLK_IDX_FETCH_FBI               55
#define CELL_GCM_PM_GCLK_IDX_FETCH_SYS               56
#define CELL_GCM_PM_GCLK_VAB_CMD_LOAD                72
#define CELL_GCM_PM_GCLK_VAB_CMD_TRI                 74
#define CELL_GCM_PM_GCLK_RASTERIZEDPIXELCOUNT_1      80
#define CELL_GCM_PM_GCLK_RASTERIZEDPIXELCOUNT_2      81
#define CELL_GCM_PM_GCLK_IDX_POST_TRANSFORM_CACHE_HIT_1 82
#define CELL_GCM_PM_GCLK_IDX_POST_TRANSFORM_CACHE_HIT_2 83
#define CELL_GCM_PM_GCLK_IDX_POST_TRANSFORM_CACHE_MISS_1 84
#define CELL_GCM_PM_GCLK_IDX_POST_TRANSFORM_CACHE_MISS_2 85
#define CELL_GCM_PM_GCLK_IDX_VERTEX_COUNT_1          86
#define CELL_GCM_PM_GCLK_IDX_VERTEX_COUNT_2          87
#define CELL_GCM_PM_GCLK_ZCULL_TILES_TOTAL_TESTED_1  88
#define CELL_GCM_PM_GCLK_ZCULL_TILES_TOTAL_TESTED_2  89
#define CELL_GCM_PM_GCLK_ZCULL_TILES_Z_TRIVIALLY_REJECTED_1 90
#define CELL_GCM_PM_GCLK_ZCULL_TILES_Z_TRIVIALLY_REJECTED_2 91
#define CELL_GCM_PM_GCLK_ZCULL_TILES_STENCIL_CULLED_1 92
#define CELL_GCM_PM_GCLK_ZCULL_TILES_STENCIL_CULLED_2 93
#define CELL_GCM_PM_GCLK_ZCULL_TILES_Z_TRIVIALLY_ACCEPTED_1 94
#define CELL_GCM_PM_GCLK_ZCULL_TILES_Z_TRIVIALLY_ACCEPTED_2 95
#define CELL_GCM_PM_GCLK_ZCULL_TILES_NOT_CULLED_BUT_FAILS_ZTEST_1 96
#define CELL_GCM_PM_GCLK_ZCULL_TILES_NOT_CULLED_BUT_FAILS_ZTEST_2 97
#define CELL_GCM_PM_GCLK_ZCULL_TILES_DEPTH_BOUNDS_CULLED_1 98
#define CELL_GCM_PM_GCLK_ZCULL_TILES_DEPTH_BOUNDS_CULLED_2 99
#define CELL_GCM_PM_GCLK_ZCULL_TILES_NEAR_FAR_CLIPPED_1 100
#define CELL_GCM_PM_GCLK_ZCULL_TILES_NEAR_FAR_CLIPPED_2 101
#define CELL_GCM_PM_GCLK_ZCULL_TILES_TOTAL_CULLED_1  102
#define CELL_GCM_PM_GCLK_ZCULL_TILES_TOTAL_CULLED_2  103
#define CELL_GCM_PM_GCLK_HOST2FE_METHOD_ACTIVE       104
#define CELL_GCM_PM_GCLK_HOST2FE_METHOD_IDLE         105
#define CELL_GCM_PM_GCLK_HOST2FE_METHOD_STALLING     106
#define CELL_GCM_PM_GCLK_HOST2FE_METHOD_STARVING     107
#define CELL_GCM_PM_GCLK_FE_WAITS_FOR_IDLE_GRAPHICS_PIPE 108
#define CELL_GCM_PM_GCLK_IDLE_GRAPHICS_PIPE          109
#define CELL_GCM_PM_GCLK_PROP2FE_WRITE_TEX_LABEL     111
#define CELL_GCM_PM_GCLK_XBAR2FE_WRITE_REPORT        112
#define CELL_GCM_PM_RCLK_CROP_COMP_WRITE             2
#define CELL_GCM_PM_RCLK_ZREAD_INTERLOCK_STALL       3
#define CELL_GCM_PM_RCLK_ZROP_COMP_READ_COMP_WRITE   4
#define CELL_GCM_PM_RCLK_ZROP_NO_READ_COMP_WRITE     5
#define CELL_GCM_PM_RCLK_ZROP_UNCOMP_READ_COMP_WRITE 6
#define CELL_GCM_PM_RCLK_ZROP_TOTAL_WRITTEN          7
#define CELL_GCM_PM_RCLK_CROP_SUBPACKET_COUNT        8
#define CELL_GCM_PM_SCLK_SQD_ENDSEG_ANY              5
#define CELL_GCM_PM_SCLK_SQD_ENDSEG_RASTER_TIMEOUT   7
#define CELL_GCM_PM_SCLK_SQD_ENDSEG_REGISTER_LIMIT   8
#define CELL_GCM_PM_SCLK_SQD_ENDSEG_SHADER_STATE_BUNDLE 9
#define CELL_GCM_PM_SCLK_SQD_ENDSEG_SLOT_LIMIT_FOR_SQC 10
#define CELL_GCM_PM_SCLK_SQD_ENDSEG_TRIANGLE_LIMIT   11
#define CELL_GCM_PM_SCLK_L1_TEXTURE_CACHE_REQUEST_GREATER_THAN_4_COUNT 22
#define CELL_GCM_PM_SCLK_L1_TEXTURE_CACHE_INDEX_COLLISION 23
#define CELL_GCM_PM_SCLK_TEXTURE_ANISO_COUNT_01      28
#define CELL_GCM_PM_SCLK_TEXTURE_ANISO_COUNT_02      29
#define CELL_GCM_PM_SCLK_TEXTURE_ANISO_COUNT_04      30
#define CELL_GCM_PM_SCLK_TEXTURE_ANISO_COUNT_08      32
#define CELL_GCM_PM_SCLK_TEXTURE_ANISO_COUNT_16      36
#define CELL_GCM_PM_SCLK_TEXTURE_QUAD_COUNT          37
#define CELL_GCM_PM_SCLK_L2_TEXTURE_CACHE_SET1_MISS_COUNT 45
#define CELL_GCM_PM_SCLK_L2_TEXTURE_CACHE_SET1_REQUEST_COUNT 46
#define CELL_GCM_PM_SCLK_L2_TEXTURE_CACHE_SET2_MISS_COUNT 49
#define CELL_GCM_PM_SCLK_L2_TEXTURE_CACHE_SET2_REQUEST_COUNT 50
#define CELL_GCM_PM_SCLK_2D_TRANSFER_WAITS_FOR_3D    59
#define CELL_GCM_PM_SCLK_SCT2TEX_ACTIVE              60
#define CELL_GCM_PM_SCLK_SCT2TEX_STALLING            61
#define CELL_GCM_PM_SCLK_SCT2TEX_STARVING            63
#define CELL_GCM_PM_SCLK_SHADER_ALL_TEX_NOP_QUADS    64
#define CELL_GCM_PM_SCLK_SHADER_ALL_QUADS            65
#define CELL_GCM_PM_SCLK_SHADER_FIRST_PASS_QUADS     66
#define CELL_GCM_PM_SCLK_SHADER_FIRST_PASS_TEX_NOP_QUADS 67
#define CELL_GCM_PM_SCLK_SIF_FETCH_TEXTURE_PASS_COUNT 70
#define CELL_GCM_PM_SCLK_SIF_FETCH_NO_TEXTURE_PASS_COUNT 71
#define CELL_GCM_PM_SCLK_FINERASTERTILES_COVERED     74
#define CELL_GCM_PM_SCLK_FINERASTERTILES_FASTZ       76
#define CELL_GCM_PM_SCLK_FINERASTERBUNDLES           77
#define CELL_GCM_PM_SCLK_L2_TEXTURE_CACHE_SET3_MISS_COUNT 104
#define CELL_GCM_PM_SCLK_L2_TEXTURE_CACHE_SET3_REQUEST_COUNT 105
#define CELL_GCM_PM_SCLK_L2_TEXTURE_CACHE_SET4_MISS_COUNT 108
#define CELL_GCM_PM_SCLK_L2_TEXTURE_CACHE_SET4_REQUEST_COUNT 109
#define CELL_GCM_PM_SCLK_PREROP_VALID_PIXEL          116
#define CELL_GCM_PM_SCLK_PREROP_VALID_PACKET         116
#define CELL_GCM_PM_SCLK_SQD_ENDSEG_SLOT_LIMIT_FOR_QUAD 117
#define CELL_GCM_PM_SCLK_PREROP_FE_FLUSH_ACTIVE      119
#define CELL_GCM_PM_SCLK_SHADER_TOTAL_QUADS          123
#define CELL_GCM_PM_SCLK_SHADER_TOTAL_FIRST_PASS_QUADS 124
#define CELL_GCM_PM_MCLK_FB_RW_COUNT1                1
#define CELL_GCM_PM_MCLK_FB_RW_COUNT2                2
#define CELL_GCM_PM_MCLK_FB_IDLE                     7
#define CELL_GCM_PM_MCLK_FB_RW_IDLE                  27
#define CELL_GCM_PM_MCLK_FB_STALLED                  30
#define CELL_GCM_PM_MCLK_COMPRESSED_FAST_CLEAR       31
#define CELL_GCM_PM_MCLK_EXPANDED_FAST_CLEAR         32
#define CELL_GCM_PM_MCLK_FB_COMPRESSED_WRITE         33
#define CELL_GCM_PM_MCLK_FB_NORMAL_WRITE             34
#define CELL_GCM_PM_MCLK_FB_COMPRESSED_READ          38
#define CELL_GCM_PM_MCLK_FB_NORMAL_READ              40
#define CELL_GCM_PM_MCLK_FB_CROP_READ                41
#define CELL_GCM_PM_MCLK_FB_CROP_WRITE               42
#define CELL_GCM_PM_MCLK_FB_TEXTURE_READ             46
#define CELL_GCM_PM_MCLK_FB_ZROP_READ                47
#define CELL_GCM_PM_MCLK_FB_HOST_READ                128
#define CELL_GCM_PM_MCLK_FB_HOST_WRITE               129
#define CELL_GCM_PM_MCLK_FB_GRFE_READ                132
#define CELL_GCM_PM_MCLK_FB_GRFE_WRITE               133
#define CELL_GCM_PM_ICLK_SYS_NORMAL_WRITE            5
#define CELL_GCM_PM_ICLK_SYS_NORMAL_READ             7
#define CELL_GCM_PM_ICLK_DEBUG_AUDIO_TRANSFER        8

#endif /* __PS3TC_CELL_GCM_PM_H__ */
