/* cell/mouse/error.h - mouse library return codes. */
#ifndef PS3TC_CELL_MOUSE_ERROR_H
#define PS3TC_CELL_MOUSE_ERROR_H

#include <cell/error.h>

#define CELL_MOUSE_OK CELL_OK
#define CELL_MOUSE_ERROR_FATAL CELL_ERROR_CAST(0x80121201)
#define CELL_MOUSE_ERROR_INVALID_PARAMETER CELL_ERROR_CAST(0x80121202)
#define CELL_MOUSE_ERROR_ALREADY_INITIALIZED CELL_ERROR_CAST(0x80121203)
#define CELL_MOUSE_ERROR_UNINITIALIZED CELL_ERROR_CAST(0x80121204)
#define CELL_MOUSE_ERROR_RESOURCE_ALLOCATION_FAILED CELL_ERROR_CAST(0x80121205)
#define CELL_MOUSE_ERROR_DATA_READ_FAILED CELL_ERROR_CAST(0x80121206)
#define CELL_MOUSE_ERROR_NO_DEVICE CELL_ERROR_CAST(0x80121207)
#define CELL_MOUSE_ERROR_SYS_SETTING_FAILED CELL_ERROR_CAST(0x80121208)

#endif /* PS3TC_CELL_MOUSE_ERROR_H */
