#ifndef PS3DK_PSGL_REPORT_H
#define PS3DK_PSGL_REPORT_H

#include <PSGL/export.h>
#include <GLES/gl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum PSGL_REPORT_ENUMS {
    PSGL_REPORT_UNKNOWN = 0,
    PSGL_REPORT_VERSION,
    PSGL_REPORT_DEBUG,
    PSGL_REPORT_ASSERT,
    PSGL_REPORT_GL_ERROR,
    PSGL_REPORT_MISSING_STATE,
    PSGL_REPORT_VERTEX_SLOW_PATH,
    PSGL_REPORT_VERTEX_DATA_WARNING,
    PSGL_REPORT_COPY_TEXTURE_SLOW_PATH,
    PSGL_REPORT_COPY_TEXTURE_WARNING,
    PSGL_REPORT_TEXTURE_COPY_BACK,
    PSGL_REPORT_TEXTURE_REALLOC,
    PSGL_REPORT_FP32_FILTERING,
    PSGL_REPORT_TEXTURE_INCOMPLETE,
    PSGL_REPORT_FRAMEBUFFER_INCOMPLETE,
    PSGL_REPORT_FRAMEBUFFER_UNSUPPORTED,
    PSGL_REPORT_CG_ERROR,
    PSGL_REPORT_CG_PROFILE_DEPRECATED,
    PSGL_REPORT_BUFFER_OBJECT_OUT_OF_BOUNDS,
    PSGL_REPORT_GPU_MEMORY_ALLOC,
    PSGL_REPORT_GPU_MEMORY_FREE,
    PSGL_REPORT_GPU_MEMORY_ASYNC_FREE,
    PSGL_REPORT_HOST_MEMORY_ALLOC,
    PSGL_REPORT_HOST_MEMORY_FREE,
    PSGL_REPORT_HOST_MEMORY_ASYNC_FREE,
    PSGL_REPORT_MALLOC_MEMORY_ALLOC,
    PSGL_REPORT_MALLOC_MEMORY_REALLOC,
    PSGL_REPORT_MALLOC_MEMORY_FREE,
    PSGL_REPORT_TEXTURE_CONVERSION,
    PSGL_REPORT_RESC,
    PSGL_REPORT_RESC_FLIP_ERROR,
    PSGL_REPORT_COMMAND_RECORD_CALLBACK,
    PSGL_REPORT_MAX
} PSGL_REPORT_ENUMS;

typedef enum PSGL_REPORT_CLASSES {
    PSGL_REPORT_CLASS_UNKNOWN = 0,
    PSGL_REPORT_CLASS_DEBUG,
    PSGL_REPORT_CLASS_INFO,
    PSGL_REPORT_CLASS_WARNING,
    PSGL_REPORT_CLASS_PERFORMANCE_INFO = 8,
    PSGL_REPORT_CLASS_PERFORMANCE_WARNING,
    PSGL_REPORT_CLASS_PERFORMANCE_CRITICAL,
    PSGL_REPORT_CLASS_API_ERROR = 16,
    PSGL_REPORT_CLASS_GL_CRITICAL_ERROR,
    PSGL_REPORT_CLASS_INTERNAL_ERROR,
    PSGL_REPORT_CLASS_USER_CRITICAL_ERROR,
    PSGL_REPORT_CLASS_GPU_MEMORY_INFO = 24,
    PSGL_REPORT_CLASS_HOST_MEMORY_INFO,
    PSGL_REPORT_CLASS_MALLOC_MEMORY_INFO
} PSGL_REPORT_CLASSES;

#define PSGL_REPORT_ALL                 0xffffffffu
#define PSGL_REPORT_MISC_CLASSES        0x000000ffu
#define PSGL_REPORT_PERFORMANCE_CLASSES 0x0000ff00u
#define PSGL_REPORT_ERROR_CLASSES       0x00ff0000u
#define PSGL_REPORT_MEMORY_INFO_CLASSES 0xff000000u

typedef void (*PSGLreportFunction)(GLenum report, GLuint id, const char *message);

PSGL_EXPORT void psglDisableReport(GLenum report);
PSGL_EXPORT void psglEnableReport(GLenum report);
PSGL_EXPORT GLboolean psglIsReportEnabled(GLenum report);
PSGL_EXPORT void psglSetReportClassMask(GLuint reportClassMask);
PSGL_EXPORT GLuint psglGetReportClassMask(void);
PSGL_EXPORT PSGLreportFunction psglGetReportFunction(void);
PSGL_EXPORT void psglSetReportFunction(PSGLreportFunction function);
PSGL_EXPORT void psglSetDefaultReportParameters(GLboolean showEnums);

#ifdef __cplusplus
}
#endif

#endif /* PS3DK_PSGL_REPORT_H */
