//! Export-table source generation: a library YAML -> the `exports.S` a module
//! assembles into its `.lib.ent` record.
//!
//! This is the mirror of `stubgen`. `stubgen` renders the *importer* side (the
//! `.lib.stub` record, FNID table, trampolines and compact OPDs a caller links
//! against); `entgen` renders the *exporter* side (the `.lib.ent` record, NID
//! table and address table a module publishes).
//!
//! Deliberately thin: it emits the `<sys/prx_module.h>` macros rather than raw
//! section directives, so the byte layout of an export record lives in exactly
//! one place. A hand-written `exports.S` and a generated one are the same
//! thing, which is what makes the round trip
//! (`prx-gen exports` -> YAML -> `entgen`) checkable.

use crate::db::{ExportKind, Library};
use anyhow::{bail, Result};
use std::fmt::Write;

/// Turn a library name into an identifier usable as a macro tag.
///
/// The tag only names assembler labels local to the file, so any stable
/// mangling will do; it just has to be a valid identifier and unique within
/// the file, and we emit one library per file.
fn tag_for(library: &str) -> String {
    let mut out: String = library
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if out.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(true) {
        out.insert(0, '_');
    }
    out
}

/// Render a module's export table as a `.S` file.
pub fn render_exports(lib: &Library) -> Result<String> {
    if lib.exports.is_empty() {
        bail!(
            "library '{}' declares no exports; a .lib.ent record with num_func = 0 \
             would register a library that publishes nothing",
            lib.library
        );
    }

    for e in &lib.exports {
        match e.kind {
            ExportKind::Function => {}
            ExportKind::Variable => bail!(
                "export '{}' in library '{}' is a variable. Variable exports need a \
                 PRX_EXPORT_VAR macro and the num_var half of the record, which \
                 <sys/prx_module.h> does not implement yet.",
                e.name,
                lib.library
            ),
            ExportKind::Tlsvar => bail!(
                "export '{}' in library '{}' is a TLS variable. The loader logs an \
                 error and ignores any record with num_tlsvar set, so emitting one \
                 would produce a module that looks fine and silently drops the \
                 export.",
                e.name,
                lib.library
            ),
        }
    }

    let tag = tag_for(&lib.library);
    let mut out = String::with_capacity(1024);

    writeln!(out, "/* Auto-generated by `nidgen entgen` - do not edit by hand. */").ok();
    writeln!(out, "/* Library: {} */", lib.library).ok();
    writeln!(out, "/* Exports: {} function(s) */", lib.exports.len()).ok();
    writeln!(out).ok();
    writeln!(out, "#include <sys/prx_module.h>").ok();
    writeln!(out).ok();
    writeln!(out, "PRX_LIBRARY_BEGIN({}, \"{}\")", tag, lib.library).ok();
    for e in &lib.exports {
        writeln!(out, "\tPRX_EXPORT_FUNC({}, 0x{:08x})", e.name, e.nid).ok();
    }
    writeln!(out, "PRX_LIBRARY_END({})", tag).ok();

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::Export;

    fn lib_with(exports: Vec<Export>) -> Library {
        Library {
            library: "hello_prx".into(),
            version: 1,
            module: "hello_prx".into(),
            archive_name: None,
            exports,
            imports: Vec::new(),
        }
    }

    fn func(name: &str, nid: u32) -> Export {
        Export {
            name: name.into(),
            nid,
            fnid: None,
            signature: String::new(),
            kind: ExportKind::Function,
            ordinal: None,
            notes: None,
            aliases: Vec::new(),
            impl_status: Default::default(),
        }
    }

    #[test]
    fn renders_the_macros_a_human_would_have_written() {
        let s = render_exports(&lib_with(vec![func("prx_add", 0xe1f4_c294)])).unwrap();
        assert!(s.contains("#include <sys/prx_module.h>"));
        assert!(s.contains("PRX_LIBRARY_BEGIN(hello_prx, \"hello_prx\")"));
        assert!(s.contains("PRX_EXPORT_FUNC(prx_add, 0xe1f4c294)"));
        assert!(s.contains("PRX_LIBRARY_END(hello_prx)"));
    }

    #[test]
    fn nids_are_padded_to_eight_hex_digits() {
        // 0x42 must not render as 0x42 — the macro emits a .long, and a
        // short literal reads as a mistake to anyone diffing against a
        // hand-written file.
        let s = render_exports(&lib_with(vec![func("f", 0x42)])).unwrap();
        assert!(s.contains("0x00000042"), "got: {s}");
    }

    #[test]
    fn an_empty_library_is_refused() {
        let err = render_exports(&lib_with(vec![])).unwrap_err().to_string();
        assert!(err.contains("no exports"), "got: {err}");
    }

    #[test]
    fn tls_exports_are_refused_rather_than_silently_dropped() {
        let mut e = func("tls_thing", 1);
        e.kind = ExportKind::Tlsvar;
        let err = render_exports(&lib_with(vec![e])).unwrap_err().to_string();
        assert!(err.contains("TLS"), "got: {err}");
    }

    #[test]
    fn variable_exports_are_refused_until_the_macro_exists() {
        let mut e = func("some_var", 1);
        e.kind = ExportKind::Variable;
        let err = render_exports(&lib_with(vec![e])).unwrap_err().to_string();
        assert!(err.contains("variable"), "got: {err}");
    }

    #[test]
    fn tags_are_valid_identifiers() {
        assert_eq!(tag_for("hello_prx"), "hello_prx");
        assert_eq!(tag_for("cell-Gcm"), "cell_Gcm");
        assert_eq!(tag_for("3d"), "_3d");
    }
}
