//! Emit PPU assembly that produces PSL1GHT/Sony-compatible stub archives.
//!
//! The PS3 PRX loader + sprxlinker + `lv2.ld` expect specific section names
//! in the final linked ELF — not per-library scoped variants.  The stub
//! archive we produce here matches that contract exactly, which is the same
//! contract PSL1GHT's `sprx/common/libexport.c` has always targeted:
//!
//! ```text
//!   .data.sceFStub.<library>   one 4-byte slot per export + anchor symbol;
//!                              each slot is a pointer to the trampoline
//!                              `__<name>` symbol (defined elsewhere — by
//!                              PSL1GHT's SPRX build, not here).
//!   .rodata.sceResident        4-byte version word + the library-name
//!                              null-terminated string.
//!   .lib.stub                  one 44-byte prx_header per library, pointing
//!                              at the name string, the first fnid, and the
//!                              fstub table anchor.
//!   .rodata.sceFNID            one 4-byte NID per export.
//! ```
//!
//! Earlier versions of this module emitted `.lib.stub.<library>` + `b <sym>`
//! placeholders — a format that never matched the linker script and would
//! never have produced a loader-compatible SELF.  Do not regress to that.
//!
//! The `__<name>` trampolines are intentionally out of scope here: they live
//! in the SPRX build for each library (they're ~32 bytes of PPC64 code that
//! loads the patched stub slot and branches through it).  A stub archive
//! produced by this module is the "import half" that user code links
//! against; the SPRX/crt build is the "export half" that defines the
//! trampolines and the runtime library behind them.

use crate::db::Library;
use std::fmt::Write;

/// Render a library's stub archive source as a single `.S` file.
pub fn render_library(lib: &Library) -> String {
    let mut out = String::with_capacity(4096);

    writeln!(out, "# Auto-generated by nidgen — do not edit by hand.").ok();
    writeln!(out, "# Library: {}", lib.library).ok();
    writeln!(out, "# Module:  {}", lib.module).ok();
    writeln!(out, "# Exports: {}", lib.exports.len()).ok();
    writeln!(out).ok();
    writeln!(out, "\t.file \"{}.S\"", lib.library).ok();
    writeln!(out, "\t.machine cell").ok();
    writeln!(out).ok();

    // 1. Anchor for the fstub section.  Zero-size object at the top of the
    //    per-library fstub section; the `.lib.stub` header's `fstub` pointer
    //    references this so the loader can walk the slot table.
    let fstub_section = format!(".data.sceFStub.{}", lib.library);
    writeln!(out, "\t.section \"{}\",\"aw\"", fstub_section).ok();
    writeln!(out, "\t.align 2").ok();
    writeln!(out, "\t.type scefstub, @object").ok();
    writeln!(out, "\t.size scefstub, 0").ok();
    writeln!(out, "scefstub:").ok();
    writeln!(out).ok();

    // 2. Library name string + resident header.
    let name_sym = format!("__nidgen_{}_name", lib.library);
    let version_sym = format!("__nidgen_{}_version", lib.library);
    writeln!(out, "\t.section \".rodata.sceResident\",\"a\"").ok();
    writeln!(out, "\t.align 2").ok();
    writeln!(out, "\t.type {}, @object", version_sym).ok();
    writeln!(out, "\t.size {}, 4", version_sym).ok();
    writeln!(out, "{}:", version_sym).ok();
    writeln!(out, "\t.long 0").ok();
    let name_bytes = lib.library.as_bytes();
    writeln!(out, "\t.type {}, @object", name_sym).ok();
    writeln!(out, "\t.size {}, {}", name_sym, name_bytes.len() + 1).ok();
    writeln!(out, "{}:", name_sym).ok();
    writeln!(out, "\t.asciz \"{}\"", lib.library).ok();
    writeln!(out).ok();

    // 3. The 44-byte `.lib.stub` header.  sprxlinker walks these structs to
    //    count imports and patch the fnidcount field; the order of fields
    //    matches `libexport.c`'s `prx_header` exactly (u32, u16, u16, u32,
    //    u32, name*, fnid*, fstub*, u32, u32, u32, u32).
    //
    //    header2 = number of exports per PSL1GHT convention; sprxlinker
    //    recomputes this from the fnid spacing, so either value is fine on
    //    well-formed inputs.  We use the Sony-observed 0x0009 family (count
    //    of exports); dumps across all 97 stub archives show variations in
    //    the low byte that correspond to export counts, so this is indeed
    //    an export count.
    let header_sym = format!("__nidgen_{}_header", lib.library);
    let first_fnid_sym = lib
        .exports
        .first()
        .map(|e| format!("{}_fnid", e.name))
        .unwrap_or_else(|| "0".into());
    writeln!(out, "\t.section \".lib.stub\",\"aw\"").ok();
    writeln!(out, "\t.align 2").ok();
    writeln!(out, "\t.type {}, @object", header_sym).ok();
    writeln!(out, "\t.size {}, 44", header_sym).ok();
    writeln!(out, "{}:", header_sym).ok();
    writeln!(out, "\t.4byte 0x2c000001       # size=44, version=1").ok();
    writeln!(out, "\t.2byte {}              # export count", lib.exports.len()).ok();
    writeln!(out, "\t.2byte 0").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out, "\t.4byte {}", name_sym).ok();
    writeln!(out, "\t.4byte {}", first_fnid_sym).ok();
    writeln!(out, "\t.4byte scefstub").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out).ok();

    // 4. Per-export stub slot + fnid.  Each export gets:
    //      <name>_stub  in .data.sceFStub.<library>, 4 bytes, = &__<name>.
    //      <name>_fnid  in .rodata.sceFNID,         4 bytes, = NID.
    //    The `__<name>` trampoline is an extern — PSL1GHT's SPRX build
    //    defines it in each library's sprx.c + sprx crt.  User code that
    //    calls `<name>` branches through `.sceStub.text:<name>` (generated
    //    by the GCC PLT / PSL1GHT's librt), which loads the stub slot
    //    pointer from `<name>_stub` and jumps through it.  The stub slot
    //    starts out pointing at `__<name>` (the trampoline).  The PRX
    //    loader patches it at runtime to point at the real implementation
    //    in the resolved SPRX module.
    for e in &lib.exports {
        let stub_sym = format!("{}_stub", e.name);
        let fnid_sym = format!("{}_fnid", e.name);
        let trampoline_sym = format!("__{}", e.name);

        writeln!(out, "\t.globl {}", stub_sym).ok();
        writeln!(out, "\t.section \"{}\"", fstub_section).ok();
        writeln!(out, "\t.align 2").ok();
        writeln!(out, "\t.type {}, @object", stub_sym).ok();
        writeln!(out, "\t.size {}, 4", stub_sym).ok();
        writeln!(out, "{}:", stub_sym).ok();
        writeln!(out, "\t.4byte {}", trampoline_sym).ok();

        writeln!(out, "\t.globl {}", fnid_sym).ok();
        writeln!(out, "\t.section \".rodata.sceFNID\",\"a\"").ok();
        writeln!(out, "\t.align 2").ok();
        writeln!(out, "\t.type {}, @object", fnid_sym).ok();
        writeln!(out, "\t.size {}, 4", fnid_sym).ok();
        writeln!(out, "{}:", fnid_sym).ok();
        writeln!(out, "\t.4byte 0x{:08x}", e.nid).ok();
        writeln!(out).ok();
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::{Export, Library};

    fn sample() -> Library {
        Library {
            library: "cellPad".into(),
            version: 1,
            module: "sys_io".into(),
            exports: vec![
                Export {
                    name: "cellPadInit".into(),
                    nid: 0x1e7e_b5b3,
                    fnid: None,
                    signature: "int cellPadInit(uint32_t max_ports)".into(),
                    ordinal: None,
                    notes: None,
                    impl_status: crate::db::ImplStatus::Unknown,
                },
                Export {
                    name: "cellPadEnd".into(),
                    nid: 0x2ba1_4c6b,
                    fnid: None,
                    signature: "int cellPadEnd(void)".into(),
                    ordinal: None,
                    notes: None,
                    impl_status: crate::db::ImplStatus::Unknown,
                },
            ],
            imports: vec![],
        }
    }

    #[test]
    fn emits_sony_compatible_sections() {
        let s = render_library(&sample());
        // Header preamble.
        assert!(s.contains("Library: cellPad"));
        // Sony-compatible section names.
        assert!(s.contains(".data.sceFStub.cellPad"), "missing fstub section");
        assert!(s.contains(".rodata.sceResident"), "missing resident section");
        assert!(s.contains(".rodata.sceFNID"), "missing fnid section");
        assert!(s.contains(".lib.stub\""), "missing lib.stub section");
        // Must NOT emit the obsolete per-library .lib.stub.<library> form.
        assert!(
            !s.contains(".lib.stub.cellPad"),
            "regressed to obsolete .lib.stub.<library> format"
        );
        // Library name in sceResident.
        assert!(s.contains("\"cellPad\""));
        // Each export has a _stub + _fnid pair pointing at __<name>.
        assert!(s.contains("cellPadInit_stub:"));
        assert!(s.contains("__cellPadInit"));
        assert!(s.contains("cellPadInit_fnid:"));
        assert!(s.contains("0x1e7eb5b3"));
        assert!(s.contains("cellPadEnd_stub:"));
        assert!(s.contains("__cellPadEnd"));
        assert!(s.contains("0x2ba14c6b"));
        // The prx_header struct body.
        assert!(s.contains("0x2c000001"), "missing prx_header magic word");
        assert!(s.contains(".2byte 2"), "export count should be 2");
    }

    #[test]
    fn empty_library_still_well_formed() {
        let lib = Library {
            library: "empty".into(),
            version: 1,
            module: "empty".into(),
            exports: vec![],
            imports: vec![],
        };
        let s = render_library(&lib);
        // No crash; still emits a header with export count 0 and fnid=0.
        assert!(s.contains(".2byte 0              # export count"));
    }
}
