//! Emit PPU assembly stub files from a NID database.
//!
//! For each exported symbol, emits a small `.s` file that the PRX loader uses
//! to resolve the dynamic import at module-load time. The layout follows the
//! conventions used by PSL1GHT and the Sony SDK:
//!
//! ```text
//!     .section .lib.stub.<library>, "ax"
//!     .align 2
//!     .globl <symbol>
//! <symbol>:
//!     .long 0x00000000       # relocation slot (patched by PRX loader)
//!     .long <NID>            # import NID
//!     b    <symbol>          # placeholder; loader rewrites this branch
//! ```
//!
//! Multiple stubs are aggregated into a single `.s` file per library so the
//! resulting `.a` archive has a single member per library.

use crate::db::Library;
use std::fmt::Write;

/// Render every export of the library as a single assembly source file.
pub fn render_library(lib: &Library) -> String {
    let mut out = String::with_capacity(1024);

    writeln!(out, "# Auto-generated by nidgen — do not edit by hand.").ok();
    writeln!(out, "# Library: {}", lib.library).ok();
    writeln!(out, "# Module:  {}", lib.module).ok();
    writeln!(out, "# Exports: {}", lib.exports.len()).ok();
    writeln!(out).ok();

    writeln!(out, "    .section .lib.stub.{}, \"ax\"", lib.library).ok();
    writeln!(out, "    .align 2").ok();
    writeln!(out).ok();

    for e in &lib.exports {
        writeln!(out, "    .globl {}", e.name).ok();
        writeln!(out, "    .type  {}, @function", e.name).ok();
        writeln!(out, "{}:", e.name).ok();
        writeln!(out, "    .long 0x00000000      # loader-patched slot").ok();
        writeln!(out, "    .long 0x{:08x}      # NID", e.nid).ok();
        writeln!(out, "    b     {}           # placeholder", e.name).ok();
        writeln!(out, "    .size {},.-{}", e.name, e.name).ok();
        writeln!(out).ok();
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::{Export, Library};

    fn sample() -> Library {
        Library {
            library: "cellPad".into(),
            version: 1,
            module: "sys_io".into(),
            exports: vec![
                Export {
                    name: "cellPadInit".into(),
                    nid: 0x1e7e_b5b3,
                    fnid: None,
                    signature: "int cellPadInit(uint32_t max_ports)".into(),
                    ordinal: None,
                    notes: None,
                },
                Export {
                    name: "cellPadEnd".into(),
                    nid: 0x2ba14c6b,
                    fnid: None,
                    signature: "int cellPadEnd(void)".into(),
                    ordinal: None,
                    notes: None,
                },
            ],
            imports: vec![],
        }
    }

    #[test]
    fn emits_header_and_each_export() {
        let s = render_library(&sample());
        assert!(s.contains("Library: cellPad"));
        assert!(s.contains("cellPadInit:"));
        assert!(s.contains("0x1e7eb5b3"));
        assert!(s.contains("cellPadEnd:"));
        assert!(s.contains("0x2ba14c6b"));
        assert!(s.contains(".section .lib.stub.cellPad"));
    }
}
