//! Emit PPU assembly that produces complete cell-SDK-compatible stub archives.
//!
//! The PS3 PRX loader + sprxlinker + `lv2.ld` expect specific section names
//! in the final linked ELF — not per-library scoped variants.  The reference
//! cell-SDK stub archives ship one per-export `.o` whose sections add up to
//! a self-contained import surface; PSL1GHT's `sprx/common/libexport.c` +
//! `exports.S` reproduce the same surface, split across two source files.
//! This module reproduces all of it in a single emit:
//!
//! ```text
//!   .data.sceFStub.<library>   anchor + one 4-byte slot per export.
//!                              Each slot is initialised to the trampoline
//!                              `__<name>` (the PRX loader patches it at
//!                              module load to the real function descriptor
//!                              of the resolved SPRX entry).
//!   .rodata.sceResident        4-byte version word + library-name C-string.
//!   .lib.stub                  one 44-byte prx_header per library, pointing
//!                              at the name string, the first fnid, and the
//!                              fstub table anchor.
//!   .rodata.sceFNID            per-library anchor symbol + one 4-byte NID
//!                              per export.
//!   .sceStub.text              per-export ~60-byte PPC64 trampoline that
//!                              reads `<name>_stub` (function descriptor),
//!                              loads entry+TOC, and branches via `bctrl`.
//!   .opd                       per-export 24-byte function descriptor so
//!                              the externally-callable C symbol `<name>`
//!                              resolves to the trampoline.
//! ```
//!
//! The emitted archive is therefore self-contained: no PSL1GHT SPRX support
//! is required to link against it.  This is what makes stub-only cell-SDK
//! libraries (libsysutil_screenshot, libsysutil_ap, imejp, subdisplay,
//! music\*) work without a hand-written wrapper.
//!
//! Earlier versions of this module emitted `.lib.stub.<library>` + `b <sym>`
//! placeholders — a format that never matched the linker script and would
//! never have produced a loader-compatible SELF.  Do not regress to that.

use crate::db::Library;
use std::fmt::Write;

/// Render a library's stub archive source as a single `.S` file.
pub fn render_library(lib: &Library) -> String {
    let mut out = String::with_capacity(4096);

    writeln!(out, "# Auto-generated by nidgen — do not edit by hand.").ok();
    writeln!(out, "# Library: {}", lib.library).ok();
    writeln!(out, "# Module:  {}", lib.module).ok();
    writeln!(out, "# Exports: {}", lib.exports.len()).ok();
    writeln!(out).ok();
    writeln!(out, "\t.file \"{}.S\"", lib.library).ok();
    writeln!(out, "\t.machine cell").ok();
    writeln!(out).ok();

    // 1. Anchor for the fstub section.  Zero-size object at the top of the
    //    per-library fstub section; the `.lib.stub` header's `fstub` pointer
    //    references this so the loader can walk the slot table.
    let fstub_section = format!(".data.sceFStub.{}", lib.library);
    writeln!(out, "\t.section \"{}\",\"aw\"", fstub_section).ok();
    writeln!(out, "\t.align 2").ok();
    writeln!(out, "\t.type scefstub, @object").ok();
    writeln!(out, "\t.size scefstub, 0").ok();
    writeln!(out, "scefstub:").ok();
    writeln!(out).ok();

    // 2. Library name string + resident header.
    let name_sym = format!("__nidgen_{}_name", lib.library);
    let version_sym = format!("__nidgen_{}_version", lib.library);
    writeln!(out, "\t.section \".rodata.sceResident\",\"a\"").ok();
    writeln!(out, "\t.align 2").ok();
    writeln!(out, "\t.type {}, @object", version_sym).ok();
    writeln!(out, "\t.size {}, 4", version_sym).ok();
    writeln!(out, "{}:", version_sym).ok();
    writeln!(out, "\t.long 0").ok();
    let name_bytes = lib.library.as_bytes();
    writeln!(out, "\t.type {}, @object", name_sym).ok();
    writeln!(out, "\t.size {}, {}", name_sym, name_bytes.len() + 1).ok();
    writeln!(out, "{}:", name_sym).ok();
    writeln!(out, "\t.asciz \"{}\"", lib.library).ok();
    writeln!(out).ok();

    // 3. The 44-byte `.lib.stub` header.  sprxlinker walks these structs to
    //    count imports and patch the fnidcount field; the order of fields
    //    matches `libexport.c`'s `prx_header` exactly (u32, u16, u16, u32,
    //    u32, name*, fnid*, fstub*, u32, u32, u32, u32).
    //
    //    header2 = number of exports per PSL1GHT convention; sprxlinker
    //    recomputes this from the fnid spacing, so either value is fine on
    //    well-formed inputs.  We use the reference-observed 0x0009 family (count
    //    of exports); dumps across all 97 stub archives show variations in
    //    the low byte that correspond to export counts, so this is indeed
    //    an export count.
    let header_sym = format!("__nidgen_{}_header", lib.library);
    let fnid_anchor_ref = format!("__nidgen_{}_fnid_anchor", lib.library);
    writeln!(out, "\t.section \".lib.stub\",\"aw\"").ok();
    writeln!(out, "\t.align 2").ok();
    writeln!(out, "\t.type {}, @object", header_sym).ok();
    writeln!(out, "\t.size {}, 44", header_sym).ok();
    writeln!(out, "{}:", header_sym).ok();
    writeln!(out, "\t.4byte 0x2c000001       # size=44, version=1").ok();
    writeln!(out, "\t.2byte {}              # export count", lib.exports.len()).ok();
    writeln!(out, "\t.2byte 0").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out, "\t.4byte {}", name_sym).ok();
    writeln!(out, "\t.4byte {}", fnid_anchor_ref).ok();
    writeln!(out, "\t.4byte scefstub").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out, "\t.4byte 0").ok();
    writeln!(out).ok();

    // 4. Anchor symbol for the per-library .rodata.sceFNID block — matches
    //    PSL1GHT's `LIBRARY_SYMBOL` convention so the .lib.stub header's
    //    `fnid` field has a deterministic start address.
    let fnid_anchor = format!("__nidgen_{}_fnid_anchor", lib.library);
    writeln!(out, "\t.section \".rodata.sceFNID\",\"a\"").ok();
    writeln!(out, "\t.align 2").ok();
    writeln!(out, "\t.globl {}", fnid_anchor).ok();
    writeln!(out, "\t.type {}, @object", fnid_anchor).ok();
    writeln!(out, "\t.size {}, 0", fnid_anchor).ok();
    writeln!(out, "{}:", fnid_anchor).ok();
    writeln!(out).ok();

    // 5. Per-export quartet: slot, fnid, trampoline, opd descriptor.
    //
    //    <name>_stub   .data.sceFStub.<library>  4B    = &__<name>
    //    <name>_fnid   .rodata.sceFNID           4B    = NID
    //    __<name>      .sceStub.text             ~60B  trampoline (saves LR/r2,
    //                                                  loads <name>_stub as a
    //                                                  function descriptor,
    //                                                  branches via bctrl,
    //                                                  restores, returns)
    //    <name>        .opd                      24B   { __<name>, .TOC.@tocbase, 0 }
    //
    //    The PRX loader patches <name>_stub at module load to point at the
    //    real entry's function descriptor in the resolved SPRX.  Until then
    //    the slot still points at __<name> itself, and calling it would
    //    re-enter the trampoline forever (stack overflow).  This matches
    //    PSL1GHT's existing fallback behaviour; it relies on the loader
    //    actually patching every slot.
    for e in &lib.exports {
        let stub_sym = format!("{}_stub", e.name);
        let fnid_sym = format!("{}_fnid", e.name);
        let tramp_sym = format!("__{}", e.name);

        // 5a. Stub slot.
        writeln!(out, "\t.globl {}", stub_sym).ok();
        writeln!(out, "\t.section \"{}\"", fstub_section).ok();
        writeln!(out, "\t.align 2").ok();
        writeln!(out, "\t.type {}, @object", stub_sym).ok();
        writeln!(out, "\t.size {}, 4", stub_sym).ok();
        writeln!(out, "{}:", stub_sym).ok();
        writeln!(out, "\t.4byte {}", tramp_sym).ok();

        // 5b. FNID.
        writeln!(out, "\t.globl {}", fnid_sym).ok();
        writeln!(out, "\t.section \".rodata.sceFNID\",\"a\"").ok();
        writeln!(out, "\t.align 2").ok();
        writeln!(out, "\t.type {}, @object", fnid_sym).ok();
        writeln!(out, "\t.size {}, 4", fnid_sym).ok();
        writeln!(out, "{}:", fnid_sym).ok();
        writeln!(out, "\t.4byte 0x{:08x}", e.nid).ok();

        // 5c. Trampoline — frame-less wrapping stub matching GCC's
        //     LR/TOC save convention under our ELF64 + ILP32 hybrid ABI.
        //
        //     GCC emits prologues that save LR @ caller_sp+16 and TOC @
        //     caller_sp+40 (LP64 ELFv1 reserved-slot convention, retained
        //     under our hybrid because TOC discipline matches LP64).  The
        //     callee-reserved area at sp+16/+40 is therefore guaranteed
        //     unused by the caller's locals.  The PSL1GHT EXPORT macro in
        //     sprx/common/exports.S follows the same convention.
        //
        //     The earlier "frame-less" emit used sp+24 for LR — wrong by
        //     8 bytes; the slot at sp+24 sits inside whatever local area
        //     the caller allocated and got clobbered.  This is the actual
        //     Layer 11 root cause; see project_layer11_init_signal_dispatch.
        //
        //     SP is unchanged across the call so the SPRX (LP64 callee)
        //     finds stack args where the caller put them.  No need for a
        //     stwu since none of the SPRX exports we emit take >8 args.
        writeln!(out, "\t.section \".sceStub.text\",\"ax\"").ok();
        writeln!(out, "\t.align 2").ok();
        writeln!(out, "\t.globl {}", tramp_sym).ok();
        writeln!(out, "\t.type {}, @function", tramp_sym).ok();
        writeln!(out, "{}:", tramp_sym).ok();
        writeln!(out, "\tmflr   0").ok();
        writeln!(out, "\tstw    0,16(1)").ok();          // LR -> caller's reserved callee-LR slot
        writeln!(out, "\tstw    2,40(1)").ok();          // TOC -> caller's reserved TOC slot
        writeln!(out, "\tlis    12,{}@ha", stub_sym).ok();
        writeln!(out, "\tlwz    12,{}@l(12)", stub_sym).ok();
        writeln!(out, "\tlwz    0,0(12)").ok();          // SPRX entry
        writeln!(out, "\tlwz    2,4(12)").ok();          // SPRX TOC
        writeln!(out, "\tmtctr  0").ok();
        writeln!(out, "\tbctrl").ok();                   // call SPRX
        writeln!(out, "\tlwz    2,40(1)").ok();          // restore caller TOC
        writeln!(out, "\tlwz    0,16(1)").ok();          // restore caller LR
        writeln!(out, "\tmtlr   0").ok();
        writeln!(out, "\tblr").ok();
        writeln!(out, "\t.size {}, .-{}", tramp_sym, tramp_sym).ok();

        // 5d. OPD function descriptor for the externally callable symbol.
        //     Compact 8-byte format: [entry_ea_32, toc_ea_32]. Matches the
        //     pattern GCC emits under POWERPC_CELL64LV2 — single .long
        //     directive with both slots, and `.TOC.` (not `.TOC.@tocbase`)
        //     so the assembler picks R_PPC64_ADDR32 rather than the
        //     8-byte R_PPC64_TOC.
        writeln!(out, "\t.section \".opd\",\"aw\"").ok();
        writeln!(out, "\t.align 2").ok();
        writeln!(out, "\t.globl {}", e.name).ok();
        writeln!(out, "{}:", e.name).ok();
        writeln!(out, "\t.long {}, .TOC.", tramp_sym).ok();
        writeln!(out, "\t.previous").ok();
        writeln!(out, "\t.type {}, @function", e.name).ok();
        writeln!(out, "\t.size {}, 8", e.name).ok();
        writeln!(out).ok();
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::{Export, Library};

    fn sample() -> Library {
        Library {
            library: "cellPad".into(),
            version: 1,
            module: "sys_io".into(),
            archive_name: None,
            exports: vec![
                Export {
                    name: "cellPadInit".into(),
                    nid: 0x1e7e_b5b3,
                    fnid: None,
                    signature: "int cellPadInit(uint32_t max_ports)".into(),
                    ordinal: None,
                    notes: None,
                    impl_status: crate::db::ImplStatus::Unknown,
                },
                Export {
                    name: "cellPadEnd".into(),
                    nid: 0x2ba1_4c6b,
                    fnid: None,
                    signature: "int cellPadEnd(void)".into(),
                    ordinal: None,
                    notes: None,
                    impl_status: crate::db::ImplStatus::Unknown,
                },
            ],
            imports: vec![],
        }
    }

    #[test]
    fn emits_cell_sdk_compatible_sections() {
        let s = render_library(&sample());
        // Header preamble.
        assert!(s.contains("Library: cellPad"));
        // Cell-SDK-compatible section names.
        assert!(s.contains(".data.sceFStub.cellPad"), "missing fstub section");
        assert!(s.contains(".rodata.sceResident"), "missing resident section");
        assert!(s.contains(".rodata.sceFNID"), "missing fnid section");
        assert!(s.contains(".lib.stub\""), "missing lib.stub section");
        assert!(s.contains(".sceStub.text"), "missing sceStub.text trampoline section");
        assert!(s.contains(".opd"), "missing opd descriptor section");
        // Must NOT emit the obsolete per-library .lib.stub.<library> form.
        assert!(
            !s.contains(".lib.stub.cellPad"),
            "regressed to obsolete .lib.stub.<library> format"
        );
        // Library name in sceResident.
        assert!(s.contains("\"cellPad\""));
        // Each export has the full quartet: stub slot, fnid, trampoline, opd.
        assert!(s.contains("cellPadInit_stub:"));
        assert!(s.contains("__cellPadInit:"), "trampoline label missing");
        assert!(s.contains("cellPadInit_fnid:"));
        assert!(s.contains("0x1e7eb5b3"));
        assert!(s.contains("cellPadEnd_stub:"));
        assert!(s.contains("__cellPadEnd:"), "trampoline label missing");
        assert!(s.contains("0x2ba14c6b"));
        // OPD descriptor lines for both externally-callable symbols.
        assert!(s.contains(".long __cellPadInit, .TOC."), "missing opd entry EA+TOC");
        // TOC slot is in the same .long line, checked above.
        // FNID anchor symbol.
        assert!(s.contains("__nidgen_cellPad_fnid_anchor"));
        // The prx_header struct body.
        assert!(s.contains("0x2c000001"), "missing prx_header magic word");
        assert!(s.contains(".2byte 2"), "export count should be 2");
        // Trampoline body is the frame-less form matching GCC's LR/TOC
        // save convention under our ELF64+ILP32 hybrid ABI.  GCC saves LR
        // @ sp+16 and TOC @ sp+40 (LP64 ELFv1 reserved slots), so the
        // trampoline uses the same offsets to avoid clobbering caller
        // locals.  Width is `stw` (4-byte) because pointers are 32-bit.
        assert!(s.contains("bctrl"), "trampoline missing bctrl");
        assert!(!s.contains("stdu") && !s.contains("stwu"),
                "trampoline must be frame-less (would shift SP + break stack-arg passing)");
        assert!(s.contains("stw    0,16(1)") || s.contains("stw 0,16(1)"),
                "trampoline must save caller LR at sp+16");
        assert!(s.contains("stw    2,40(1)") || s.contains("stw 2,40(1)"),
                "trampoline must save caller TOC at sp+40");
        assert!(!s.contains("std    0,") && !s.contains("std 0,"),
                "ILP32 trampoline must not use 8-byte std for LR save");
        assert!(s.contains("cellPadInit_stub@ha"), "trampoline missing stub-slot load");
    }

    #[test]
    fn empty_library_still_well_formed() {
        let lib = Library {
            library: "empty".into(),
            version: 1,
            module: "empty".into(),
            archive_name: None,
            exports: vec![],
            imports: vec![],
        };
        let s = render_library(&lib);
        // No crash; still emits a header with export count 0 and fnid=0.
        assert!(s.contains(".2byte 0              # export count"));
    }
}
