/*
 * PS3 Custom Toolchain - cell/font/ps3fontset.h
 *
 * CELL_FONT_TYPE_* constants: enumerated font-face and font-set
 * identifiers for cellFont.
 */
#ifndef _PS3DK_CELL_FONT_PS3FONTSET_H_
#define _PS3DK_CELL_FONT_PS3FONTSET_H_

#ifdef __cplusplus
extern "C" {
#endif

#define CELL_FONT_TYPE_RODIN_SANS_SERIF_LATIN              (0x00000000)
#define CELL_FONT_TYPE_RODIN_SANS_SERIF_LIGHT_LATIN        (0x00000001)
#define CELL_FONT_TYPE_RODIN_SANS_SERIF_BOLD_LATIN         (0x00000002)
#define CELL_FONT_TYPE_RODIN_SANS_SERIF_LATIN2             (0x00000018)
#define CELL_FONT_TYPE_RODIN_SANS_SERIF_LIGHT_LATIN2       (0x00000019)
#define CELL_FONT_TYPE_RODIN_SANS_SERIF_BOLD_LATIN2        (0x0000001a)
#define CELL_FONT_TYPE_MATISSE_SERIF_LATIN                 (0x00000020)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_JAPANESE            (0x00000008)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_LIGHT_JAPANESE      (0x00000009)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_BOLD_JAPANESE       (0x0000000a)
#define CELL_FONT_TYPE_YD_GOTHIC_KOREAN                    (0x0000000c)
#define CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_LATIN            (0x00000040)
#define CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_LATIN2           (0x00000041)
#define CELL_FONT_TYPE_VAGR_SANS_SERIF_ROUND               (0x00000043)
#define CELL_FONT_TYPE_VAGR_SANS_SERIF_ROUND_LATIN2        (0x00000044)
#define CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_JAPANESE         (0x00000048)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_JP_SET              (0x00000100)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_LATIN_SET           (0x00000101)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN_SET           (0x00000104)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN2_SET          (0x00000204)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_RODIN2_SET              (0x00000201)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_DFHEI5_SET              (0x00000108)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_DFHEI5_RODIN_SET        (0x00000109)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_DFHEI5_RODIN2_SET       (0x00000209)
#define CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_TCH_SET          (0x0000010a)
#define CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN_TCH_SET    (0x0000010b)
#define CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN2_TCH_SET   (0x0000020b)
#define CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_SCH_SET          (0x0000010c)
#define CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN_SCH_SET    (0x0000010d)
#define CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN2_SCH_SET   (0x0000020d)
#define CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_RSANS_SET                      (0x00300104)
#define CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_RSANS_SET                (0x00300105)
#define CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_JP_SET                   (0x00300107)
#define CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_YG_DFHEI5_RSANS_SET            (0x00300109)
#define CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_YG_DFHEI5_RSANS_SET      (0x0030010F)
#define CELL_FONT_TYPE_VAGR_SEURAT_CAPIE_MARU_GOTHIC_RSANS_SET           (0x00300124)
#define CELL_FONT_TYPE_VAGR_SEURAT_CAPIE_MARU_GOTHIC_YG_DFHEI5_RSANS_SET (0x00300129)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_LIGHT_SET               (0x00040100)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_RODIN_LIGHT_SET         (0x00040101)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_RODIN2_LIGHT_SET        (0x00040201)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN_LIGHT_SET            (0x00040104)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN2_LIGHT_SET           (0x00040204)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_BOLD_SET                (0x00070100)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_RODIN_BOLD_SET          (0x00070101)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_RODIN2_BOLD_SET         (0x00070201)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN_BOLD_SET             (0x00070104)
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN2_BOLD_SET            (0x00070204)
#define CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_RSANS2_SET                        (0x00300204)
#define CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_RSANS2_SET                  (0x00300205)
#define CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_YG_DFHEI5_RSANS2_SET              (0x00300209)
#define CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_YG_DFHEI5_RSANS2_SET        (0x0030020F)
#define CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_YG_DFHEI5_VAGR2_SET         (0x00300229)
#define CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_VAGR2_SET                   (0x00300224)
#define CELL_FONT_TYPE_DEFAULT_GOTHIC_SET               CELL_FONT_TYPE_NEWRODIN_GOTHIC_LATIN_SET
#define CELL_FONT_TYPE_DEFAULT_GOTHIC_LATIN_SET         CELL_FONT_TYPE_NEWRODIN_GOTHIC_LATIN_SET
#define CELL_FONT_TYPE_DEFAULT_GOTHIC_JP_SET            CELL_FONT_TYPE_NEWRODIN_GOTHIC_JP_SET
#define CELL_FONT_TYPE_DEFAULT_SANS_SERIF               CELL_FONT_TYPE_RODIN_SANS_SERIF_LATIN
#define CELL_FONT_TYPE_DEFAULT_SERIF                    CELL_FONT_TYPE_MATISSE_SERIF_LATIN
#define CELL_FONT_TYPE_GOTHIC_JAPANESE_CJK_JP_SET       CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_DFHEI5_SET
#define CELL_FONT_TYPE_GOTHIC_JAPANESE_CJK_LATIN_SET    CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_DFHEI5_RODIN_SET
#define CELL_FONT_TYPE_GOTHIC_TCHINESE_CJK_JP_SET       CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_TCH_SET
#define CELL_FONT_TYPE_GOTHIC_TCHINESE_CJK_LATIN_SET    CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN_TCH_SET
#define CELL_FONT_TYPE_GOTHIC_SCHINESE_CJK_JP_SET       CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_SCH_SET
#define CELL_FONT_TYPE_GOTHIC_SCHINESE_CJK_LATIN_SET    CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN_SCH_SET
#define CELL_FONT_TYPE_ROUND_SANS_EUROPEAN_SET                        CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_LATIN
#define CELL_FONT_TYPE_ROUND_SANS_EUROPEAN_CASUAL_SET                 CELL_FONT_TYPE_VAGR_SANS_SERIF_ROUND
#define CELL_FONT_TYPE_GOTHIC_JAPANESE_JP_SET                         CELL_FONT_TYPE_NEWRODIN_GOTHIC_JAPANESE
#define CELL_FONT_TYPE_GOTHIC_JAPANESE_LATIN_SET                      CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN_SET
#define CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_JP_SET                    CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_JAPANESE
#define CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_LATIN_SET                 CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_RSANS_SET
#define CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_CASUAL_JP_SET             CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_JP_SET
#define CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_CASUAL_LATIN_SET          CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_RSANS_SET
#define CELL_FONT_TYPE_ROUND_SANS_EUROPEAN_CASUAL_J_LATIN_SET         CELL_FONT_TYPE_VAGR_SEURAT_CAPIE_MARU_GOTHIC_RSANS_SET
#define CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_CJK_LATIN_SET             CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_YG_DFHEI5_RSANS_SET
#define CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_CASUAL_CJK_LATIN_SET      CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_YG_DFHEI5_RSANS_SET
#define CELL_FONT_TYPE_ROUND_SANS_EUROPEAN_CJK_LATIN_SET              CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_CJK_LATIN_SET
#define CELL_FONT_TYPE_ROUND_SANS_EUROPEAN_CASUAL_CJK_LATIN_SET       CELL_FONT_TYPE_VAGR_SEURAT_CAPIE_MARU_GOTHIC_YG_DFHEI5_RSANS_SET
#define CELL_FONT_TYPE_DEFAULT_SANS_SERIF_LIGHT           CELL_FONT_TYPE_RODIN_SANS_SERIF_LIGHT_LATIN
#define CELL_FONT_TYPE_DEFAULT_SANS_SERIF_BOLD            CELL_FONT_TYPE_RODIN_SANS_SERIF_BOLD_LATIN
#define CELL_FONT_TYPE_GOTHIC_LIGHT_JAPANESE_JP_SET       CELL_FONT_TYPE_NEWRODIN_GOTHIC_LIGHT_JAPANESE
#define CELL_FONT_TYPE_GOTHIC_LIGHT_JAPANESE_LATIN_SET    CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN_LIGHT_SET
#define CELL_FONT_TYPE_GOTHIC_BOLD_JAPANESE_JP_SET        CELL_FONT_TYPE_NEWRODIN_GOTHIC_BOLD_JAPANESE
#define CELL_FONT_TYPE_GOTHIC_BOLD_JAPANESE_LATIN_SET     CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN_BOLD_SET
#define CELL_FONT_TYPE_GOTHIC_JK_JP_SET                   CELL_FONT_TYPE_DEFAULT_GOTHIC_JP_SET
#define CELL_FONT_TYPE_GOTHIC_JK_LATIN_SET                CELL_FONT_TYPE_DEFAULT_GOTHIC_LATIN_SET
#define CELL_FONT_TYPE_GOTHIC_LIGHT_JK_JP_SET             CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_LIGHT_SET
#define CELL_FONT_TYPE_GOTHIC_LIGHT_JK_LATIN_SET          CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_RODIN_LIGHT_SET
#define CELL_FONT_TYPE_GOTHIC_BOLD_JK_JP_SET              CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_BOLD_SET
#define CELL_FONT_TYPE_GOTHIC_BOLD_JK_LATIN_SET           CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_RODIN_BOLD_SET
#define CELL_FONT_TYPE_DEFAULT_SANS_SERIF_LATIN2          CELL_FONT_TYPE_RODIN_SANS_SERIF_LATIN2
#define CELL_FONT_TYPE_DEFAULT_SANS_SERIF_LIGHT_LATIN2    CELL_FONT_TYPE_RODIN_SANS_SERIF_LIGHT_LATIN2
#define CELL_FONT_TYPE_DEFAULT_SANS_SERIF_BOLD_LATIN2     CELL_FONT_TYPE_RODIN_SANS_SERIF_BOLD_LATIN2
#define CELL_FONT_TYPE_GOTHIC_JAPANESE_LATIN2_SET         CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN2_SET
#define CELL_FONT_TYPE_GOTHIC_LIGHT_JAPANESE_LATIN2_SET   CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN2_LIGHT_SET
#define CELL_FONT_TYPE_GOTHIC_BOLD_JAPANESE_LATIN2_SET    CELL_FONT_TYPE_NEWRODIN_GOTHIC_RODIN2_BOLD_SET
#define CELL_FONT_TYPE_GOTHIC_JK_LATIN2_SET               CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_RODIN2_SET
#define CELL_FONT_TYPE_GOTHIC_LIGHT_JK_LATIN2_SET         CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_RODIN2_LIGHT_SET
#define CELL_FONT_TYPE_GOTHIC_BOLD_JK_LATIN2_SET          CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_RODIN2_BOLD_SET
#define CELL_FONT_TYPE_GOTHIC_JAPANESE_CJK_LATIN2_SET     CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_DFHEI5_RODIN2_SET
#define CELL_FONT_TYPE_GOTHIC_TCHINESE_CJK_LATIN2_SET     CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN2_TCH_SET
#define CELL_FONT_TYPE_GOTHIC_SCHINESE_CJK_LATIN2_SET     CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN2_SCH_SET
#define CELL_FONT_TYPE_ROUND_SANS_EUROPEAN_LATIN2                    CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_LATIN2
#define CELL_FONT_TYPE_ROUND_SANS_EUROPEAN_CASUAL_LATIN2             CELL_FONT_TYPE_VAGR_SANS_SERIF_ROUND_LATIN2
#define CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_LATIN2_SET               CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_RSANS2_SET
#define CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_CASUAL_LATIN2_SET        CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_RSANS2_SET
#define CELL_FONT_TYPE_ROUND_SANS_EUROPEAN_CASUAL_J_LATIN2_SET       CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_VAGR2_SET
#define CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_CJK_LATIN2_SET           CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_YG_DFHEI5_RSANS2_SET
#define CELL_FONT_TYPE_MARU_GOTHIC_JAPANESE_CASUAL_CJK_LATIN2_SET    CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_YG_DFHEI5_RSANS2_SET
#define CELL_FONT_TYPE_ROUND_SANS_EUROPEAN_CJK_LATIN2_SET            CELL_FONT_TYPE_SEURAT_MARU_GOTHIC_YG_DFHEI5_RSANS2_SET
#define CELL_FONT_TYPE_ROUND_SANS_EUROPEAN_CASUAL_CJK_LATIN2_SET     CELL_FONT_TYPE_SEURAT_CAPIE_MARU_GOTHIC_YG_DFHEI5_VAGR2_SET
#define CELL_FONT_MAP_FONT    (0x0)
#define CELL_FONT_MAP_UNICODE (0x1)

#ifdef __cplusplus
}
#endif

#endif
