#ifndef __PS3DK_SCE_HL_SPURS_HLSPURSJOBNOTIFICATION_H__
#define __PS3DK_SCE_HL_SPURS_HLSPURSJOBNOTIFICATION_H__

#include <sce/hl/spurs/job.h>

#endif /* __PS3DK_SCE_HL_SPURS_HLSPURSJOBNOTIFICATION_H__ */
