#ifndef __PS3DK_SCE_HL_SPURS_HLSPURSCOMMANDLISTDISPATCHER_H__
#define __PS3DK_SCE_HL_SPURS_HLSPURSCOMMANDLISTDISPATCHER_H__

#include <sce/hl/spurs/command_list_dispatcher.h>

#endif /* __PS3DK_SCE_HL_SPURS_HLSPURSCOMMANDLISTDISPATCHER_H__ */
