// tests/simdmath-inline/source/main.c
//
// PPU side of the simdmath-inline test.
//
// Spawns the embedded SPU ELF that calls sincosf4 / divf4 / rsqrtf4 /
// divf4fast.  The SPU has no libm on its side and no libsimdmath.a on its
// link line (see CMakeLists - LIBS = sputhread only), so if the inline
// headers are not actually installed into $(PS3DK)/spu/include/simdmath/
// the SPU ELF will not link and this test will fail at the CMake build
// step before we even reach main().
//
// At runtime all we need to check is that the SPU's exit code is 0; the
// PPU returns that as its own exit code directly.

#include <stdio.h>
#include <stdint.h>
#include <ppu-types.h>
#include <sys/spu.h>

#include "simdmath_inline_spu_bin.h"

#define ptr2ea(x) ((u64)((uintptr_t)(x)))

// A "completion" word the SPU signals so the PPU knows to join.
static volatile u32 spu_done __attribute__((aligned(128))) = 0;

int main (int argc, char **argv)
{
    (void)argc; (void)argv;
    u32 cause, status;
    sysSpuImage image;
    u32 group_id, thread_id;

    printf ("simdmath-inline: ppu main starting\n");

    sysSpuInitialize (6, 0);
    sysSpuImageImport (&image, simdmath_inline_spu_bin, 0);

    sysSpuThreadGroupAttribute grpattr = {
        .nsize     = 8,
        .name      = (const char *)ptr2ea("simd_inline_grp"),
        .type      = 0,
        .option.ct = 0,
    };
    sysSpuThreadGroupCreate (&group_id, 1, 100, &grpattr);

    sysSpuThreadAttribute attr = {
        .name   = (const char *)ptr2ea("simd_inline_thr"),
        .nsize  = 9,
        .option = SPU_THREAD_ATTR_NONE,
    };
    sysSpuThreadArgument arg = {
        .arg0 = ptr2ea (&spu_done),
        .arg1 = 0,
        .arg2 = 0,
        .arg3 = 0,
    };

    sysSpuThreadInitialize (&thread_id, group_id, 0, &image, &attr, &arg);
    printf ("simdmath-inline: starting spu thread group\n");
    sysSpuThreadGroupStart (group_id);

    while (spu_done == 0) { /* spin */ }

    sysSpuThreadGroupJoin (group_id, &cause, &status);
    sysSpuImageClose (&image);

    printf ("simdmath-inline: spu finished cause=%u status=%u done=%u\n",
            cause, status, spu_done);

    /* The SPU's sys_spu_thread_exit code lands in the status word via
     * the LV2 join path (see samples/spu/hello-spu).  We do not need to
     * distinguish "all checks passed" from "some checks failed" - a
     * failure on the SPU side will show up as a non-zero status here.
     * Return the SPU's exit code directly so the harness can assert on it. */
    return (int)(status & 0xFFFF);
}

// The embedded SPU ELF binary (generated by bin2s into
// simdmath_inline_spu_bin.h with symbol `simdmath_inline_spu_bin`) must
// be visible to this PPU translation unit.  The header is generated at
// CMake build time by ps3_add_spu_image().
