#!/usr/bin/env python3
"""Generate sdk/include/cell/gcm/gcm_command_cpp_explicit.h.

cell::Gcm::CellGcmContext is the C++ form of a GCM command context: it has
the layout of CellGcmContextData and one member per context-taking command,
named without the cellGcm prefix (context.SetVertexDataArray(...) is
cellGcmSetVertexDataArray(&context, ...)).  The members are generated from
the SDK's own command headers so the class never falls behind them: every
`static inline` function named cellGcm* whose first parameter is a
CellGcmContextData pointer becomes a forwarding member.

  scripts/gen-gcm-context-cpp.py            write the header
  scripts/gen-gcm-context-cpp.py --check    exit 1 if it is out of date
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INC = ROOT / "sdk" / "include"
OUT = INC / "cell" / "gcm" / "gcm_command_cpp_explicit.h"
SOURCES = sorted((INC / "cell" / "gcm").glob("*.h")) + [INC / "cell" / "gcm.h"]

FUNC = re.compile(
    r"static\s+inline\s+(?P<ret>[A-Za-z_][\w\s\*]*?)\s*\b(?P<name>cellGcm\w+)\s*"
    r"\((?P<params>[^()]*(?:\([^()]*\)[^()]*)*)\)\s*\{",
    re.S,
)
CTX = re.compile(r"^\s*(?:struct\s+)?CellGcmContextData\s*\*\s*\w+\s*$")


def split_params(text):
    out, depth, cur = [], 0, ""
    for ch in text:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def param_name(p):
    p = re.sub(r"\[[^\]]*\]\s*$", "", p).strip()
    m = re.search(r"(\w+)\s*$", p)
    return m.group(1) if m else None


def strip_comments(s):
    s = re.sub(r"/\*.*?\*/", " ", s, flags=re.S)
    return re.sub(r"//[^\n]*", " ", s)


def collect():
    members, seen = [], set()
    for path in SOURCES:
        if path == OUT:
            continue
        text = strip_comments(path.read_text(encoding="utf-8"))
        for m in FUNC.finditer(text):
            params = split_params(" ".join(m.group("params").split()))
            if not params or not CTX.match(params[0]):
                continue
            rest = params[1:]
            if rest == ["void"]:
                rest = []
            names = [param_name(p) for p in rest]
            if any(n is None for n in names):
                continue
            ret = " ".join(m.group("ret").split())
            # one member per signature: the same command can be defined in
            # more than one header (guarded), under other parameter names
            types = tuple(" ".join(p[: p.rfind(n)].split()) + p[p.rfind(n) + len(n):]
                          for p, n in zip(rest, names))
            key = (m.group("name"), types)
            if key in seen:
                continue
            seen.add(key)
            members.append((m.group("name"), ret, rest, names))
    members.sort(key=lambda t: (t[0], len(t[2])))
    return members


def render(members):
    lines = [
        "/* cell/gcm/gcm_command_cpp_explicit.h - cell::Gcm::CellGcmContext.",
        " *",
        " * GENERATED by scripts/gen-gcm-context-cpp.py from the SDK's GCM command",
        " * headers; do not edit.  One member per context-taking cellGcm* command,",
        " * named without the prefix: context.SetVertexDataArray(...) is",
        " * cellGcmSetVertexDataArray(&context, ...).  The class adds no data, so a",
        " * CellGcmContextData (gCellGcmCurrentContext, say) can be used as one.",
        " */",
        "#ifndef __PS3DK_CELL_GCM_COMMAND_CPP_EXPLICIT_H__",
        "#define __PS3DK_CELL_GCM_COMMAND_CPP_EXPLICIT_H__",
        "",
        "#ifdef __cplusplus",
        "",
        "namespace cell { namespace Gcm {",
        "",
        "struct CellGcmContext : public CellGcmContextData",
        "{",
    ]
    for name, ret, params, names in members:
        member = name[len("cellGcm"):]
        call = "::%s(this%s)" % (name, "".join(", " + n for n in names))
        body = ("return %s;" % call) if ret != "void" else ("%s;" % call)
        lines.append("    %s %s(%s)" % (ret, member, ", ".join(params)))
        lines.append("    { %s }" % body)
    lines += [
        "};",
        "",
        "} }   /* namespace cell::Gcm */",
        "",
        "#endif /* __cplusplus */",
        "",
        "#endif /* __PS3DK_CELL_GCM_COMMAND_CPP_EXPLICIT_H__ */",
        "",
    ]
    return "\n".join(lines)


def main():
    text = render(collect())
    if "--check" in sys.argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("gcm_command_cpp_explicit.h is out of date: run scripts/gen-gcm-context-cpp.py")
            return 1
        print("gcm_command_cpp_explicit.h is up to date (%d members)" % text.count("    { "))
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote %s (%d members)" % (OUT.relative_to(ROOT), text.count("    { ")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
