#!/usr/bin/env bash
# PS3 Custom Toolchain — version generator (single source of truth).
#
# Reads the current git state and emits the SDK version in one of several
# formats consumed by the various build systems in this repo.
#
# Versioning rules:
#   - Source of truth is the most recent annotated tag matching v[0-9]+.[0-9]+.[0-9]+.
#   - If HEAD is exactly that tag, the version is the tag verbatim.
#   - If HEAD is past that tag, patch += commits-since-tag (so untagged commits
#     get monotonically increasing patch numbers without manual bumping).
#   - If there is no tag yet, the version is v0.0.0.
#   - If the working tree is dirty, "+dirty" is appended to the human-readable
#     formats (plain, header string macro). Numeric components are unaffected.
#
# Output formats (--format=...):
#   plain        v0.4.2                   default; for shell consumers
#   bare         0.4.2                    no leading 'v'; for Cargo.toml
#   cmake        set(...) lines           for CMake include()
#   header       C #defines               for sdk/include/.../sdk_version.h
#   json         {"version":"v0.4.2",...} for tooling
#
# Components exposed in cmake/header/json:
#   PS3SDK_VERSION             "v0.4.2"   (or "v0.4.2+dirty")
#   PS3SDK_VERSION_BARE        "0.4.2"
#   PS3SDK_VERSION_MAJOR       0
#   PS3SDK_VERSION_MINOR       4
#   PS3SDK_VERSION_PATCH       2
#   PS3SDK_VERSION_COMMIT      <full sha>
#   PS3SDK_VERSION_COMMIT_SHORT <7-char sha>
#   PS3SDK_VERSION_DIRTY       0|1

set -euo pipefail

format="plain"
for arg in "$@"; do
    case "$arg" in
        --format=*) format="${arg#--format=}" ;;
        -h|--help)
            sed -n '2,32p' "$0"
            exit 0
            ;;
        *)
            echo "version.sh: unknown argument: $arg" >&2
            exit 1
            ;;
    esac
done

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

if ! git rev-parse --git-dir >/dev/null 2>&1; then
    echo "version.sh: not inside a git repository" >&2
    exit 1
fi

# Most recent v-prefixed tag, or empty if none.
latest_tag="$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | head -n1 || true)"

if [ -z "$latest_tag" ]; then
    major=0
    minor=0
    patch=0
    commits_since_tag="$(git rev-list --count HEAD 2>/dev/null || echo 0)"
    if [ "$commits_since_tag" != "0" ]; then
        # No tag yet but there are commits: keep at v0.0.0 and let the patch
        # count express progress past the implicit zero baseline.
        patch="$commits_since_tag"
    fi
    on_tag=0
else
    # Strict vMAJOR.MINOR.PATCH parse.
    if ! [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
        echo "version.sh: latest tag '$latest_tag' is not vMAJOR.MINOR.PATCH" >&2
        exit 1
    fi
    major="${BASH_REMATCH[1]}"
    minor="${BASH_REMATCH[2]}"
    patch="${BASH_REMATCH[3]}"

    # Is HEAD exactly on the tag?
    if git describe --tags --exact-match HEAD 2>/dev/null | grep -qx "$latest_tag"; then
        on_tag=1
    else
        on_tag=0
        commits_since_tag="$(git rev-list "${latest_tag}..HEAD" --count 2>/dev/null || echo 0)"
        patch=$((patch + commits_since_tag))
    fi
fi

commit_full="$(git rev-parse HEAD 2>/dev/null || echo "")"
commit_short="$(git rev-parse --short=7 HEAD 2>/dev/null || echo "")"

dirty=0
if ! git diff --quiet --ignore-submodules HEAD 2>/dev/null; then
    dirty=1
fi
# Untracked files do not count as dirty for build identity.

version_bare="${major}.${minor}.${patch}"
version="v${version_bare}"
version_display="$version"
if [ "$dirty" = "1" ]; then
    version_display="${version}+dirty"
fi

case "$format" in
    plain)
        printf '%s\n' "$version_display"
        ;;
    bare)
        printf '%s\n' "$version_bare"
        ;;
    cmake)
        cat <<EOF
# Generated by scripts/version.sh — do not edit by hand.
set(PS3SDK_VERSION "${version_display}")
set(PS3SDK_VERSION_BARE "${version_bare}")
set(PS3SDK_VERSION_MAJOR ${major})
set(PS3SDK_VERSION_MINOR ${minor})
set(PS3SDK_VERSION_PATCH ${patch})
set(PS3SDK_VERSION_COMMIT "${commit_full}")
set(PS3SDK_VERSION_COMMIT_SHORT "${commit_short}")
set(PS3SDK_VERSION_DIRTY ${dirty})
set(PS3SDK_VERSION_ON_TAG ${on_tag})
EOF
        ;;
    header)
        cat <<EOF
/* Generated by scripts/version.sh — do not edit by hand. */
#ifndef PS3SDK_VERSION_H
#define PS3SDK_VERSION_H

#define PS3SDK_VERSION              "${version_display}"
#define PS3SDK_VERSION_BARE         "${version_bare}"
#define PS3SDK_VERSION_MAJOR        ${major}
#define PS3SDK_VERSION_MINOR        ${minor}
#define PS3SDK_VERSION_PATCH        ${patch}
#define PS3SDK_VERSION_COMMIT       "${commit_full}"
#define PS3SDK_VERSION_COMMIT_SHORT "${commit_short}"
#define PS3SDK_VERSION_DIRTY        ${dirty}
#define PS3SDK_VERSION_ON_TAG       ${on_tag}

#define PS3SDK_VERSION_NUM \\
    ((PS3SDK_VERSION_MAJOR * 10000) + (PS3SDK_VERSION_MINOR * 100) + PS3SDK_VERSION_PATCH)

#endif /* PS3SDK_VERSION_H */
EOF
        ;;
    json)
        cat <<EOF
{
  "version": "${version_display}",
  "bare": "${version_bare}",
  "major": ${major},
  "minor": ${minor},
  "patch": ${patch},
  "commit": "${commit_full}",
  "commit_short": "${commit_short}",
  "dirty": $([ "$dirty" = "1" ] && echo true || echo false),
  "on_tag": $([ "$on_tag" = "1" ] && echo true || echo false)
}
EOF
        ;;
    *)
        echo "version.sh: unknown --format=$format (want: plain|bare|cmake|header|json)" >&2
        exit 1
        ;;
esac
