#ifndef __PS3DK_CELL_CODEC_AC3_ADAPTER_H__
#define __PS3DK_CELL_CODEC_AC3_ADAPTER_H__

#include <stdint.h>

#include <cell/error.h>

#ifdef __cplusplus
extern "C" {
#endif

#define CELL_ADEC_ERROR_AC3_BUSY  CELL_ERROR_CAST(0x80612500)
#define CELL_ADEC_ERROR_AC3_EMPTY CELL_ERROR_CAST(0x80612501)
#define CELL_ADEC_ERROR_AC3_PARAM CELL_ERROR_CAST(0x80612502)
#define CELL_ADEC_ERROR_AC3_FRAME CELL_ERROR_CAST(0x80612503)

enum CELL_ADEC_AC3_WORD_SZ {
    CELL_ADEC_AC3_WORD_SZ_INT16 = 0,
    CELL_ADEC_AC3_WORD_SZ_FLOAT = 1
};

enum CELL_ADEC_AC3_OUTPUT_MODE {
    CELL_ADEC_AC3_OUTPUT_MODE_RESERVED = 0,
    CELL_ADEC_AC3_OUTPUT_MODE_1_0 = 1,
    CELL_ADEC_AC3_OUTPUT_MODE_2_0 = 2,
    CELL_ADEC_AC3_OUTPUT_MODE_3_0 = 3,
    CELL_ADEC_AC3_OUTPUT_MODE_2_1 = 4,
    CELL_ADEC_AC3_OUTPUT_MODE_3_1 = 5,
    CELL_ADEC_AC3_OUTPUT_MODE_2_2 = 6,
    CELL_ADEC_AC3_OUTPUT_MODE_3_2 = 7
};

enum CELL_ADEC_AC3_LFE {
    CELL_ADEC_AC3_LFE_NOT_PRESENT = 0,
    CELL_ADEC_AC3_LFE_PRESENT = 1
};

enum CELL_ADEC_AC3_COMPRESSION_MODE {
    CELL_ADEC_AC3_COMPRESSION_MODE_CUSTOM_ANALOG = 0,
    CELL_ADEC_AC3_COMPRESSION_MODE_CUSTOM_DIGITAL = 1,
    CELL_ADEC_AC3_COMPRESSION_MODE_LINE_OUT = 2,
    CELL_ADEC_AC3_COMPRESSION_MODE_RF_REMOD = 3
};

enum CELL_ADEC_AC3_STEREO_MODE {
    CELL_ADEC_AC3_STEREO_MODE_AUTO_DETECT = 0,
    CELL_ADEC_AC3_STEREO_MODE_DOLBY_SURROUND_COMPATIBLE = 1,
    CELL_ADEC_AC3_STEREO_MODE_STEREO = 2
};

enum CELL_ADEC_AC3_DUALMONO_MODE {
    CELL_ADEC_AC3_DUALMONO_MODE_STEREO = 0,
    CELL_ADEC_AC3_DUALMONO_MODE_LEFT_MONO = 1,
    CELL_ADEC_AC3_DUALMONO_MODE_RIGHT_MONO = 2,
    CELL_ADEC_AC3_DUALMONO_MODE_MIXED_MONO = 3
};

enum CELL_ADEC_AC3_KARAOKE_CAPABLE_MODE {
    CELL_ADEC_AC3_KARAOKE_CAPABLE_MODE_NO_VOCAL = 0,
    CELL_ADEC_AC3_KARAOKE_CAPABLE_MODE_LEFT_VOCAL = 1,
    CELL_ADEC_AC3_KARAOKE_CAPABLE_MODE_RIGHT_VOCAL = 2,
    CELL_ADEC_AC3_KARAOKE_CAPABLE_MODE_BOTH_VOCAL = 3
};

enum CELL_ADEC_AC3_INPUT_CHANNEL {
    CELL_ADEC_AC3_INPUT_CHANNEL_L = 0,
    CELL_ADEC_AC3_INPUT_CHANNEL_C = 1,
    CELL_ADEC_AC3_INPUT_CHANNEL_R = 2,
    CELL_ADEC_AC3_INPUT_CHANNEL_l = 3,
    CELL_ADEC_AC3_INPUT_CHANNEL_r = 4,
    CELL_ADEC_AC3_INPUT_CHANNEL_s = 5
};

typedef struct CellAdecParamAc3 {
    int8_t wordSize;
    int8_t outputMode;
    int8_t outLfeOn;
    float drcCutScaleFactor;
    float drcBoostScaleFactor;
    int8_t compressionMode;
    int8_t numberOfChannels;
    int8_t stereoMode;
    int8_t dualmonoMode;
    int8_t karaokeCapableMode;
    float pcmScaleFactor;
    int32_t channelPointer0;
    int32_t channelPointer1;
    int32_t channelPointer2;
    int32_t channelPointer3;
    int32_t channelPointer4;
    int32_t channelPointer5;
} CellAdecParamAc3;

#ifdef __cplusplus
}
#endif

#endif /* __PS3DK_CELL_CODEC_AC3_ADAPTER_H__ */
