/* cell/codec/atx_adapter.h - ATRAC3plus / ATRAC Advanced Lossless decoding
 * with cellAdec (CELL_ADEC_TYPE_ATRACX*): parameters, stream information,
 * channel configurations, error codes. */
#ifndef PS3TC_CELL_CODEC_ATX_ADAPTER_H
#define PS3TC_CELL_CODEC_ATX_ADAPTER_H

#include <stdint.h>
#include <cell/error.h>

#define ATRACX_EXTRA_CONFIG_DATA_SIZE                (4)
#define CELL_ADEC_ATRACX_WORD_SZ_16BIT               (0x02)
#define CELL_ADEC_ATRACX_WORD_SZ_24BIT               (0x03)
#define CELL_ADEC_ATRACX_WORD_SZ_32BIT               (0x04)
#define CELL_ADEC_ATRACX_WORD_SZ_FLOAT               (0x84)
#define CELL_ADEC_ATRACX_ATS_HDR_NOTINC              (0)
#define CELL_ADEC_ATRACX_ATS_HDR_INC                 (1)
#define CELL_ADEC_ERROR_ATX_OFFSET                   (0x80612200U)
#define CELL_ADEC_ERROR_ATX_NONE                     CELL_ERROR_CAST(0x80612200)
#define CELL_ADEC_ERROR_ATX_OK                       CELL_ERROR_CAST(0x80612200)
#define CELL_ADEC_ERROR_ATX_BUSY                     CELL_ERROR_CAST(0x80612264)
#define CELL_ADEC_ERROR_ATX_EMPTY                    CELL_ERROR_CAST(0x80612265)
#define CELL_ADEC_ERROR_ATX_ATSHDR                   CELL_ERROR_CAST(0x80612266)
#define CELL_ADEC_ERROR_ATX_NON_FATAL                CELL_ERROR_CAST(0x80612281)
#define CELL_ADEC_ERROR_ATX_NOT_IMPLE                CELL_ERROR_CAST(0x80612282)
#define CELL_ADEC_ERROR_ATX_PACK_CE_OVERFLOW         CELL_ERROR_CAST(0x80612283)
#define CELL_ADEC_ERROR_ATX_ILLEGAL_NPROCQUS         CELL_ERROR_CAST(0x80612284)
#define CELL_ADEC_ERROR_ATX_FATAL                    CELL_ERROR_CAST(0x8061228c)
#define CELL_ADEC_ERROR_ATX_ENC_OVERFLOW             CELL_ERROR_CAST(0x8061228d)
#define CELL_ADEC_ERROR_ATX_PACK_CE_UNDERFLOW        CELL_ERROR_CAST(0x8061228e)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDCT              CELL_ERROR_CAST(0x8061228f)
#define CELL_ADEC_ERROR_ATX_SYNTAX_GAINADJ           CELL_ERROR_CAST(0x80612290)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDSF              CELL_ERROR_CAST(0x80612291)
#define CELL_ADEC_ERROR_ATX_SYNTAX_SPECTRA           CELL_ERROR_CAST(0x80612292)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDWL              CELL_ERROR_CAST(0x80612293)
#define CELL_ADEC_ERROR_ATX_SYNTAX_GHWAVE            CELL_ERROR_CAST(0x80612294)
#define CELL_ADEC_ERROR_ATX_SYNTAX_SHEADER           CELL_ERROR_CAST(0x80612295)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDWL_A            CELL_ERROR_CAST(0x80612296)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDWL_B            CELL_ERROR_CAST(0x80612297)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDWL_C            CELL_ERROR_CAST(0x80612298)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDWL_D            CELL_ERROR_CAST(0x80612299)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDWL_E            CELL_ERROR_CAST(0x8061229a)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDSF_A            CELL_ERROR_CAST(0x8061229b)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDSF_B            CELL_ERROR_CAST(0x8061229c)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDSF_C            CELL_ERROR_CAST(0x8061229d)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDSF_D            CELL_ERROR_CAST(0x8061229e)
#define CELL_ADEC_ERROR_ATX_SYNTAX_IDCT_A            CELL_ERROR_CAST(0x8061229f)
#define CELL_ADEC_ERROR_ATX_SYNTAX_GC_NGC            CELL_ERROR_CAST(0x806122a0)
#define CELL_ADEC_ERROR_ATX_SYNTAX_GC_IDLEV_A        CELL_ERROR_CAST(0x806122a1)
#define CELL_ADEC_ERROR_ATX_SYNTAX_GC_IDLOC_A        CELL_ERROR_CAST(0x806122a2)
#define CELL_ADEC_ERROR_ATX_SYNTAX_GC_IDLEV_B        CELL_ERROR_CAST(0x806122a3)
#define CELL_ADEC_ERROR_ATX_SYNTAX_GC_IDLOC_B        CELL_ERROR_CAST(0x806122a4)
#define CELL_ADEC_ERROR_ATX_SYNTAX_SN_NWVS           CELL_ERROR_CAST(0x806122a5)
#define CELL_ADEC_ERROR_ATX_FATAL_HANDLE             CELL_ERROR_CAST(0x806122aa)
#define CELL_ADEC_ERROR_ATX_ASSERT_SAMPLING_FREQ     CELL_ERROR_CAST(0x806122ab)
#define CELL_ADEC_ERROR_ATX_ASSERT_CH_CONFIG_INDEX   CELL_ERROR_CAST(0x806122ac)
#define CELL_ADEC_ERROR_ATX_ASSERT_NBYTES            CELL_ERROR_CAST(0x806122ad)
#define CELL_ADEC_ERROR_ATX_ASSERT_BLOCK_NUM         CELL_ERROR_CAST(0x806122ae)
#define CELL_ADEC_ERROR_ATX_ASSERT_BLOCK_ID          CELL_ERROR_CAST(0x806122af)
#define CELL_ADEC_ERROR_ATX_ASSERT_CHANNELS          CELL_ERROR_CAST(0x806122b0)
#define CELL_ADEC_ERROR_ATX_UNINIT_BLOCK_SPECIFIED   CELL_ERROR_CAST(0x806122b1)
#define CELL_ADEC_ERROR_ATX_POSCFG_PRESENT           CELL_ERROR_CAST(0x806122b2)
#define CELL_ADEC_ERROR_ATX_BUFFER_OVERFLOW          CELL_ERROR_CAST(0x806122b3)
#define CELL_ADEC_ERROR_ATX_ILL_BLK_TYPE_ID          CELL_ERROR_CAST(0x806122b4)
#define CELL_ADEC_ERROR_ATX_UNPACK_CHANNEL_BLK_FAILED CELL_ERROR_CAST(0x806122b5)
#define CELL_ADEC_ERROR_ATX_ILL_BLK_ID_USED_1        CELL_ERROR_CAST(0x806122b6)
#define CELL_ADEC_ERROR_ATX_ILL_BLK_ID_USED_2        CELL_ERROR_CAST(0x806122b7)
#define CELL_ADEC_ERROR_ATX_ILLEGAL_ENC_SETTING      CELL_ERROR_CAST(0x806122b8)
#define CELL_ADEC_ERROR_ATX_ILLEGAL_DEC_SETTING      CELL_ERROR_CAST(0x806122b9)
#define CELL_ADEC_ERROR_ATX_ASSERT_NSAMPLES          CELL_ERROR_CAST(0x806122ba)
#define CELL_ADEC_ERROR_ATX_ILL_SYNCWORD             CELL_ERROR_CAST(0x806122bb)
#define CELL_ADEC_ERROR_ATX_ILL_SAMPLING_FREQ        CELL_ERROR_CAST(0x806122bc)
#define CELL_ADEC_ERROR_ATX_ILL_CH_CONFIG_INDEX      CELL_ERROR_CAST(0x806122bd)
#define CELL_ADEC_ERROR_ATX_RAW_DATA_FRAME_SIZE_OVER CELL_ERROR_CAST(0x806122be)
#define CELL_ADEC_ERROR_ATX_SYNTAX_ENHANCE_LENGTH_OVER CELL_ERROR_CAST(0x806122bf)
#define CELL_ADEC_ERROR_ATX_SPU_INTERNAL_FAIL        CELL_ERROR_CAST(0x806122c8)

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
	int32_t sampling_freq;
	int32_t ch_config_idx;     /* channel configuration index */
	int32_t nch_out;           /* channels to output */
	int32_t nbytes;            /* bytes per access unit */
	uint8_t extra_config_data[ATRACX_EXTRA_CONFIG_DATA_SIZE];
	int32_t bw_pcm;            /* output sample: CELL_ADEC_ATRACX_WORD_SZ_* */
	uint8_t downmix_flag;
	uint8_t au_includes_ats_hdr_flg;
} CellAdecParamAtracX;

typedef struct {
	uint32_t samplingFreq;
	uint32_t channelConfigIndex;
	uint32_t nbytes;
} CellAdecAtracXInfo;

#ifdef __cplusplus
}
#endif

#endif /* PS3TC_CELL_CODEC_ATX_ADAPTER_H */
