# PS3 Custom Toolchain — bin2s implementation script (cmake -P).
#
# Invoked by ps3_bin2s() in cmake/ps3-self.cmake at build time.  The
# function lives here so we can use execute_process(... OUTPUT_FILE)
# and file(WRITE) cross-platform without depending on bash -c or shell
# redirection — those don't work cleanly under VERBATIM custom commands
# or on a Windows native cmake / Ninja build.
#
# Inputs (passed via -D on the cmake invocation):
#   PS3_BIN2S_TOOL    Absolute path to the bin2s executable.
#   PS3_BIN2S_INPUT   Absolute path to the binary input file.
#   PS3_BIN2S_S       Output .s assembly path.
#   PS3_BIN2S_HDR     Output .h header path with extern declarations.
#   PS3_BIN2S_ID      Symbol-prefix ID (basename with dots->underscores,
#                     leading digit prefixed with '_').

cmake_minimum_required(VERSION 3.20)

foreach(var PS3_BIN2S_TOOL PS3_BIN2S_INPUT PS3_BIN2S_S PS3_BIN2S_HDR PS3_BIN2S_ID)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "ps3-bin2s-impl: ${var} not set")
    endif()
endforeach()

# Step 1: bin2s -a 64 INPUT > OUTPUT.s
execute_process(
    COMMAND "${PS3_BIN2S_TOOL}" -a 64 "${PS3_BIN2S_INPUT}"
    OUTPUT_FILE "${PS3_BIN2S_S}"
    RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "ps3-bin2s-impl: bin2s exited ${_rc} for ${PS3_BIN2S_INPUT}")
endif()

# Step 2: write the matching extern-declarations header.  Matches the
# layout PSL1GHT's data_rules emits via the bin2o macro:
#   extern const u8  <id>_end[];
#   extern const u8  <id>[];
#   extern const u32 <id>_size;
# We use unsigned char / unsigned int to avoid pulling in PSL1GHT's
# typedefs — `u8` etc. are equivalent on PowerPC64.
file(WRITE "${PS3_BIN2S_HDR}"
"/* Generated by ps3-bin2s-impl.cmake — do not edit. */\n"
"#ifndef PS3_BIN2S_${PS3_BIN2S_ID}_H\n"
"#define PS3_BIN2S_${PS3_BIN2S_ID}_H\n"
"#ifdef __cplusplus\n"
"extern \"C\" {\n"
"#endif\n"
"extern const unsigned char ${PS3_BIN2S_ID}_end[];\n"
"extern const unsigned char ${PS3_BIN2S_ID}[];\n"
"extern const unsigned int  ${PS3_BIN2S_ID}_size;\n"
"#ifdef __cplusplus\n"
"}\n"
"#endif\n"
"#endif\n")
