/* cell/keyboard/error.h - keyboard library return codes. */
#ifndef PS3TC_CELL_KEYBOARD_ERROR_H
#define PS3TC_CELL_KEYBOARD_ERROR_H

#include <cell/error.h>

#define CELL_KB_OK CELL_OK
#define CELL_KB_ERROR_FATAL CELL_ERROR_CAST(0x80121001)
#define CELL_KB_ERROR_INVALID_PARAMETER CELL_ERROR_CAST(0x80121002)
#define CELL_KB_ERROR_ALREADY_INITIALIZED CELL_ERROR_CAST(0x80121003)
#define CELL_KB_ERROR_UNINITIALIZED CELL_ERROR_CAST(0x80121004)
#define CELL_KB_ERROR_RESOURCE_ALLOCATION_FAILED CELL_ERROR_CAST(0x80121005)
#define CELL_KB_ERROR_DATA_READ_FAILED CELL_ERROR_CAST(0x80121006)
#define CELL_KB_ERROR_NO_DEVICE CELL_ERROR_CAST(0x80121007)
#define CELL_KB_ERROR_SYS_SETTING_FAILED CELL_ERROR_CAST(0x80121008)

#endif /* PS3TC_CELL_KEYBOARD_ERROR_H */
