/* cell/sync/error.h -- SPU sync return codes.
 *
 * Defines error codes and the CELL_SYNC_ERROR_* macros used by the
 * cellSync* family on SPU.
 */
#ifndef __CELL_SYNC_ERROR_H_SPU__
#define __CELL_SYNC_ERROR_H_SPU__

#include <cellstatus.h>
#include <cell/error.h>

#define CELL_SYNC_ERROR_AGAIN  CELL_ERROR_CAST(0x80410101)
#define CELL_SYNC_ERROR_INVAL  CELL_ERROR_CAST(0x80410102)
#define CELL_SYNC_ERROR_NOSYS  CELL_ERROR_CAST(0x80410103)
#define CELL_SYNC_ERROR_NOMEM  CELL_ERROR_CAST(0x80410104)
#define CELL_SYNC_ERROR_SRCH   CELL_ERROR_CAST(0x80410105)
#define CELL_SYNC_ERROR_NOENT  CELL_ERROR_CAST(0x80410106)
#define CELL_SYNC_ERROR_NOEXEC CELL_ERROR_CAST(0x80410107)
#define CELL_SYNC_ERROR_DEADLK CELL_ERROR_CAST(0x80410108)
#define CELL_SYNC_ERROR_PERM   CELL_ERROR_CAST(0x80410109)
#define CELL_SYNC_ERROR_BUSY   CELL_ERROR_CAST(0x8041010A)

#endif /* __CELL_SYNC_ERROR_H_SPU__ */
