# stage-differential.ps1 -- host-side stager for the shader-differential rig.
#
# Compiles the standing-control and probe fragment shaders with OUR
# compiler, stages the resulting containers plus the manifest into
# RPCS3's dev_hdd0, and creates the artifacts directory the guest dumps
# mismatches into.  Corpus pairs (including reference-compiled
# containers, which live only in private host-side storage and are
# staged as runtime input) are appended by later increments; this
# script owns the invariant that rows 1..2 of the manifest are the two
# standing controls, in order.
#
# The control containers travel the same runtime-load path as every
# corpus pair on purpose: controls that were embedded at build time
# would validate a different code path than the one they exist to
# validate.
#
# Compiler resolution prefers the working-tree build over the
# installed release: this rig exists to judge the compiler under
# development, and %PS3DK% is a clean release extract by standing rule.

param(
    [string]$Rsxcgc = "",
    [string]$Rpcs3Path = "C:\Users\FirebirdTA01\Desktop\Emulators\RPCS3\rpcs3.exe",
    [switch]$GeneralLowering
)

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $here "..\..\..")).Path

if (-not $Rsxcgc) {
    $candidates = @(
        (Join-Path $repoRoot "tools\rsx-cg-compiler\build\rsx-cg-compiler.exe"),
        (Join-Path $env:PS3DK "bin\rsx-cg-compiler.exe")
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) { $Rsxcgc = $c; break }
    }
    if (-not $Rsxcgc) { throw "rsx-cg-compiler.exe not found (checked working-tree build and %PS3DK%\bin); pass -Rsxcgc" }
}
Write-Host "stager: compiler = $Rsxcgc"

$hdd0 = Join-Path (Split-Path -Parent $Rpcs3Path) "dev_hdd0"
if (-not (Test-Path $hdd0)) { throw "dev_hdd0 not found at $hdd0; pass -Rpcs3Path" }
$root = Join-Path $hdd0 "shader-differential"
$controls = Join-Path $root "controls"
$artifacts = Join-Path $root "artifacts"
New-Item -ItemType Directory -Force $controls | Out-Null
New-Item -ItemType Directory -Force $artifacts | Out-Null

$extraFlags = @()
if ($GeneralLowering) { $extraFlags += "--general-lowering" }

function Compile-Shader([string]$src, [string]$dst, [string[]]$flags) {
    $srcPath = Join-Path $here "shaders\$src"
    & $Rsxcgc @flags @($extraFlags) -p sce_fp_rsx --emit-container $dst $srcPath
    if ($LASTEXITCODE -ne 0) { throw "compile failed ($LASTEXITCODE): $src" }
    # A zero-byte container is a compile that lied about succeeding --
    # refuse to stage it rather than let the guest report load-failed.
    if ((Get-Item $dst).Length -eq 0) { throw "compile produced empty container: $src" }
    Write-Host "stager: $src -> $(Split-Path -Leaf $dst) ($((Get-Item $dst).Length) bytes)"
}

# Standing controls.  control-identical is ONE container byte-copied
# twice -- the identity of the pair is established by the copy, not by
# compiling twice (compile-twice would quietly also test compiler
# determinism, which is a different question with its own harness).
Compile-Shader "sd_ctrl_a.fcg" (Join-Path $controls "ctrl_ident_a.fpo") @()
Copy-Item (Join-Path $controls "ctrl_ident_a.fpo") (Join-Path $controls "ctrl_ident_b.fpo") -Force
Compile-Shader "sd_ctrl_b.fcg" (Join-Path $controls "ctrl_mismatch_b.fpo") @()

# MAD-fusion contraction probe: our compiler against itself with
# fusion toggled.  The row's verdict answers "is the documented
# exception class to the bit-identical gate populated, as visible to
# an A8R8G8B8 RT" -- see sd_mad_probe.fcg for the channel design that
# separates contraction from coarser fastmath effects.
Compile-Shader "sd_mad_probe.fcg" (Join-Path $controls "probe_mad_fast.fpo") @()
Compile-Shader "sd_mad_probe.fcg" (Join-Path $controls "probe_mad_nofast.fpo") @("--nofastmath")

$manifest = @(
    "# shader-differential manifest -- generated by stage-differential.ps1",
    "# fields: tier|role|name|a_path|b_path|uniform_set",
    "@target emulator",
    "B|control-identical|ctrl_ident|controls/ctrl_ident_a.fpo|controls/ctrl_ident_b.fpo|0",
    "B|control-mismatch|ctrl_mismatch|controls/ctrl_ident_a.fpo|controls/ctrl_mismatch_b.fpo|0",
    "B|probe|mad_fusion|controls/probe_mad_fast.fpo|controls/probe_mad_nofast.fpo|0"
)
Set-Content -LiteralPath (Join-Path $root "manifest.txt") -Value ($manifest -join "`n") -Encoding Ascii
Write-Host "stager: manifest written ($($manifest.Count) lines) to $root"
Write-Host "stager: done -- run the shader-differential SELF under RPCS3 and scrape SDIFF| rows"
